
// ==================================================================
// BusinessUnitBoxExchangeServiceCertificatesEventArgs.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.ExchangeCore.Client
{ 
  public class BusinessUnitBoxExchangeServiceCertificatesCertificateValueInputEventArgs : global::Sungero.Presentation.ValueInputEventArgs<global::Sungero.CoreEntities.ICertificate>
  {
    public BusinessUnitBoxExchangeServiceCertificatesCertificateValueInputEventArgs(global::Sungero.CoreEntities.ICertificate oldValue, global::Sungero.CoreEntities.ICertificate newValue, global::Sungero.Domain.Shared.IEntity entity, global::Sungero.Domain.Shared.IPropertyInfo propertyInfo): base(oldValue, newValue, entity, propertyInfo) { }
  }

}
