
// ==================================================================
// ContractualDocumentBaseTracking.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Docflow.Server
{


  public class ContractualDocumentBaseTracking :
    global::Sungero.Docflow.Server.OfficialDocumentTracking, global::Sungero.Docflow.IContractualDocumentBaseTracking
  {
    public static new readonly global::System.Guid ClassTypeGuid = global::System.Guid.Parse("ed823dc9-aa71-4b3e-9fd2-3be45aaef872");

    public override global::System.Guid TypeGuid
    {
      get { return global::Sungero.Docflow.Server.ContractualDocumentBaseTracking.ClassTypeGuid; }
    }

    public override string TypeName
    {
      get { return "Sungero.Docflow.IContractualDocumentBaseTracking, Sungero.Domain.Interfaces"; }
    }

    public new virtual global::Sungero.Docflow.IContractualDocumentBaseTrackingState State
    {
      get { return (global::Sungero.Docflow.IContractualDocumentBaseTrackingState)base.State; }
    }

    protected override global::Sungero.Domain.Shared.IEntityState CreateState()
    {
      return new global::Sungero.Docflow.Shared.ContractualDocumentBaseTrackingState(this);
    }

    public new virtual global::Sungero.Docflow.IContractualDocumentBaseTrackingInfo Info
    {
      get { return (global::Sungero.Docflow.IContractualDocumentBaseTrackingInfo)base.Info; }
    }










    #region Framework events



    #endregion


    public ContractualDocumentBaseTracking()
    {
    }

  }
}

// ==================================================================
// ContractualDocumentBaseTrackingHandlers.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Docflow
{

}

// ==================================================================
// ContractualDocumentBaseTrackingEventArgs.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Docflow.Server
{
}
