//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Company.Client
{
  /// <summary>
  /// Interaction logic for VisibilitySettingCollectionView.xaml.
  /// </summary>
  public partial class VisibilitySettingCollectionView : global::System.Windows.Controls.UserControl
  {
    public VisibilitySettingCollectionView()
    {
      InitializeComponent();
    }
  }
}