
// ==================================================================
// CompanyDirectiveVersions.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.RecordManagement.Client
{
  public class CompanyDirectiveVersions :
    global::Sungero.RecordManagement.Client.OrderBaseVersions, global::Sungero.RecordManagement.ICompanyDirectiveVersions
  {
    #region Fields and properties

    public static new readonly global::System.Guid ClassTypeGuid = global::System.Guid.Parse("aa3b17b3-87de-42bd-8b11-cc9dba29f58c");

    public override global::System.Guid TypeGuid
    {
      get { return global::Sungero.RecordManagement.Client.CompanyDirectiveVersions.ClassTypeGuid; }
    }

    public override string TypeName
    {
      get { return "Sungero.RecordManagement.ICompanyDirectiveVersions, Sungero.Domain.Interfaces"; }
    }

    public new global::Sungero.RecordManagement.ICompanyDirectiveVersionsState State
    {
      get
      {
        return (global::Sungero.RecordManagement.ICompanyDirectiveVersionsState)base.State;
      }
    }

    protected override global::Sungero.Domain.Shared.IEntityState CreateState()
    {
      return new global::Sungero.RecordManagement.Shared.CompanyDirectiveVersionsState(this);
    }

    public new global::Sungero.RecordManagement.ICompanyDirectiveVersionsInfo Info
    {
      get
      {
        return (global::Sungero.RecordManagement.ICompanyDirectiveVersionsInfo)base.Info;
      }
    }










    #endregion

    #region Methods

    #endregion

    #region Framework events





    #endregion

    #region Constructors







    public CompanyDirectiveVersions()
    {








    }

    #endregion

  }
}
