
// ==================================================================
// VisibilitySettingHiddenRecipientsState.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Company.Shared
{
  public class VisibilitySettingHiddenRecipientsState : 
    global::Sungero.Domain.Shared.ChildEntityState, global::Sungero.Company.IVisibilitySettingHiddenRecipientsState
  {
    public VisibilitySettingHiddenRecipientsState(global::Sungero.Company.IVisibilitySettingHiddenRecipients entity) : base(entity) { }

    public new global::Sungero.Company.IVisibilitySettingHiddenRecipientsPropertyStates Properties
    {
      get { return (global::Sungero.Company.IVisibilitySettingHiddenRecipientsPropertyStates)base.Properties; }
    }

    protected override global::Sungero.Domain.Shared.IEntityPropertyStates CreatePropertyStates(global::Sungero.Domain.Shared.IEntity entity)
    {
      return new global::Sungero.Company.Shared.VisibilitySettingHiddenRecipientsPropertyStates(entity);
    }


  }


  public class VisibilitySettingHiddenRecipientsPropertyStates : 
    global::Sungero.Domain.Shared.ChildEntityPropertyStates, global::Sungero.Company.IVisibilitySettingHiddenRecipientsPropertyStates
  {
            public global::Sungero.Domain.Shared.IPropertyState<global::Sungero.Company.IVisibilitySetting> VisibilitySetting 
            {
              get { return this.InternalVisibilitySetting; }
            }

            protected virtual global::Sungero.Domain.Shared.IPropertyState<global::Sungero.Company.IVisibilitySetting> InternalVisibilitySetting
            {
              get { return this.GetPropertyState<global::Sungero.Company.IVisibilitySetting>("VisibilitySetting"); }
            }
            public global::Sungero.Domain.Shared.IPropertyState<global::Sungero.Company.IEmployee> Recipient 
            {
              get { return this.InternalRecipient; }
            }

            protected virtual global::Sungero.Domain.Shared.IPropertyState<global::Sungero.Company.IEmployee> InternalRecipient
            {
              get { return this.GetPropertyState<global::Sungero.Company.IEmployee>("Recipient"); }
            }


    protected internal VisibilitySettingHiddenRecipientsPropertyStates(global::Sungero.Domain.Shared.IEntity entity) : base(entity) { }
  }

  public class VisibilitySettingHiddenRecipientsCollectionPropertyState<T> :
    global::Sungero.Domain.Shared.ChildEntityCollectionPropertyState<T>, global::Sungero.Company.IVisibilitySettingHiddenRecipientsCollectionPropertyState<T>
    where T : global::Sungero.Company.IVisibilitySettingHiddenRecipients
  {
    public new global::Sungero.Company.IVisibilitySettingHiddenRecipientsCollectionPropertyStates Properties
    {
      get { return (global::Sungero.Company.IVisibilitySettingHiddenRecipientsCollectionPropertyStates)base.Properties; }
    }

    protected override global::Sungero.Domain.Shared.IChildEntityCollectionPropertyStates CreatePropertyStates()
    {
      return new global::Sungero.Company.Shared.VisibilitySettingHiddenRecipientsCollectionPropertyStates(this.ChildEntityMetadata);
    }

    protected internal VisibilitySettingHiddenRecipientsCollectionPropertyState(global::Sungero.Domain.Shared.IEntity entity, string propertyName) : base(entity, propertyName) { }
  }

  public class VisibilitySettingHiddenRecipientsCollectionPropertyStates :
    global::Sungero.Domain.Shared.ChildEntityCollectionPropertyStates, global::Sungero.Company.IVisibilitySettingHiddenRecipientsCollectionPropertyStates
  {
        public global::Sungero.Domain.Shared.IChildPropertySummaryState VisibilitySetting
        {
          get { return this.GetChildPropertySummaryState("VisibilitySetting"); }
        }
        public global::Sungero.Domain.Shared.IChildPropertySummaryState Recipient
        {
          get { return this.GetChildPropertySummaryState("Recipient"); }
        }


    protected internal VisibilitySettingHiddenRecipientsCollectionPropertyStates(global::Sungero.Metadata.EntityMetadata childEntityMetadata) : base(childEntityMetadata) { }
  }
}

// ==================================================================
// VisibilitySettingHiddenRecipientsEventArgs.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Company.Shared
{  
    public class VisibilitySettingHiddenRecipientsRecipientChangedEventArgs : global::Sungero.Domain.Shared.PropertyChangedEventArgs<global::Sungero.Company.IEmployee>
    {
      public VisibilitySettingHiddenRecipientsRecipientChangedEventArgs(global::Sungero.Domain.Shared.IPropertyState<global::Sungero.Company.IEmployee> state, global::Sungero.Company.IEmployee newValue, global::Sungero.Domain.Shared.IEntity entity): base(state, newValue, entity) { }
    }

}

// ==================================================================
// VisibilitySettingHiddenRecipientsInfo.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Company.Shared
{
  public class VisibilitySettingHiddenRecipientsInfo : 
    global::Sungero.Domain.Shared.ChildEntityInfo, global::Sungero.Company.IVisibilitySettingHiddenRecipientsInfo
  {
    public VisibilitySettingHiddenRecipientsInfo(global::System.Type entityType) : base(entityType) { }

    public new global::Sungero.Company.IVisibilitySettingHiddenRecipientsPropertiesInfo Properties
    {
      get { return (global::Sungero.Company.IVisibilitySettingHiddenRecipientsPropertiesInfo)base.Properties; }
    }

    protected override global::Sungero.Domain.Shared.IEntityPropertiesInfo CreateEntityPropertiesInfo(global::System.Type entityType)
    {
      return new global::Sungero.Company.Shared.VisibilitySettingHiddenRecipientsPropertiesInfo(entityType);
    }

  }

  public class VisibilitySettingHiddenRecipientsPropertiesInfo : 
    global::Sungero.Domain.Shared.ChildEntityPropertiesInfo, global::Sungero.Company.IVisibilitySettingHiddenRecipientsPropertiesInfo
  {
        public global::Sungero.Domain.Shared.INavigationPropertyInfo<global::Sungero.Company.IVisibilitySettingInfo, global::Sungero.Company.IVisibilitySetting> VisibilitySetting 
        {
          get
          {
             var propertyMetadata = this.GetPropertyMetadata<global::Sungero.Metadata.NavigationPropertyMetadata>("VisibilitySetting");
             return new global::Sungero.Domain.Shared.NavigationPropertyInfo<global::Sungero.Company.IVisibilitySettingInfo, global::Sungero.Company.IVisibilitySetting>(propertyMetadata);
          }
        }
        public global::Sungero.Domain.Shared.INavigationPropertyInfo<global::Sungero.Company.IEmployeeInfo, global::Sungero.Company.IEmployee> Recipient 
        {
          get
          {
             var propertyMetadata = this.GetPropertyMetadata<global::Sungero.Metadata.NavigationPropertyMetadata>("Recipient");
             return new global::Sungero.Domain.Shared.NavigationPropertyInfo<global::Sungero.Company.IEmployeeInfo, global::Sungero.Company.IEmployee>(propertyMetadata);
          }
        }


    protected internal VisibilitySettingHiddenRecipientsPropertiesInfo(global::System.Type entityType) : base(entityType) { }
  }

}
