
// ==================================================================
// ReviewObserverNotificationEventArgs.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.RecordManagement.Client
{ 
}

// ==================================================================
// ReviewObserverNotificationHandlers.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.RecordManagement
{

  public partial class ReviewObserverNotificationFilteringClientHandler
    : global::Sungero.Domain.EntityFilteringClientHandler
  {
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    protected global::Sungero.RecordManagement.IReviewObserverNotificationFilterState Filter { get; private set; }

    private global::Sungero.RecordManagement.IReviewObserverNotificationFilterState _filter
    {
      get
      {
        return this.Filter;
      }
    }

    public ReviewObserverNotificationFilteringClientHandler(global::Sungero.RecordManagement.IReviewObserverNotificationFilterState filter)
    : base()
    {
      this.Filter = filter;
    }

    protected ReviewObserverNotificationFilteringClientHandler()
    {
    }

    public override void ValidateFilterPanel(global::Sungero.Domain.Client.ValidateFilterPanelEventArgs e)
    {
    }
  }


  public partial class ReviewObserverNotificationClientHandlers : global::Sungero.Workflow.NoticeClientHandlers
  {
    private global::Sungero.RecordManagement.IReviewObserverNotification _obj
    {
      get { return (global::Sungero.RecordManagement.IReviewObserverNotification)this.Entity; }
    }

    public ReviewObserverNotificationClientHandlers(global::Sungero.RecordManagement.IReviewObserverNotification entity) : base(entity)
    {
    }
  }

}

// ==================================================================
// ReviewObserverNotificationClientFunctions.g.cs
// ==================================================================

namespace Sungero.RecordManagement.Client
{
  public partial class ReviewObserverNotificationFunctions : global::Sungero.Workflow.Client.NoticeFunctions
  {
    private global::Sungero.RecordManagement.IReviewObserverNotification _obj
    {
      get { return (global::Sungero.RecordManagement.IReviewObserverNotification)this.Entity; }
    }

    public ReviewObserverNotificationFunctions(global::Sungero.RecordManagement.IReviewObserverNotification entity) : base(entity) { }
  }
}

// ==================================================================
// ReviewObserverNotificationFunctions.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.RecordManagement.Functions
{
  internal static class ReviewObserverNotification
  {
  }
}

// ==================================================================
// ReviewObserverNotificationClientPublicFunctions.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.RecordManagement.Client
{
  public class ReviewObserverNotificationClientPublicFunctions : global::Sungero.RecordManagement.Client.IReviewObserverNotificationClientPublicFunctions
  {
  }
}

// ==================================================================
// ReviewObserverNotificationActions.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.RecordManagement.Client
{
  public partial class ReviewObserverNotificationActions : global::Sungero.Workflow.Client.NoticeActions
  {
    private global::Sungero.RecordManagement.IReviewObserverNotification _obj { get { return (global::Sungero.RecordManagement.IReviewObserverNotification)this.Entity; } }
    public ReviewObserverNotificationActions(global::Sungero.RecordManagement.IReviewObserverNotification entity) : base(entity) { }
  }

  public partial class ReviewObserverNotificationCollectionActions : global::Sungero.Workflow.Client.NoticeCollectionActions
  {
    private global::System.Collections.Generic.IEnumerable<global::Sungero.RecordManagement.IReviewObserverNotification> _objs
    { 
      get { return global::System.Linq.Enumerable.Cast<global::Sungero.RecordManagement.IReviewObserverNotification>(this.Entities); }
    }
  }

  public partial class ReviewObserverNotificationAnyChildEntityActions : global::Sungero.Workflow.Client.NoticeAnyChildEntityActions
  {
  }

  public partial class ReviewObserverNotificationAnyChildEntityCollectionActions : global::Sungero.Workflow.Client.NoticeAnyChildEntityCollectionActions
  {
  }

}
