
// ==================================================================
// VerificationTaskObserversState.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.SmartProcessing.Shared
{
  public class VerificationTaskObserversState : 
    global::Sungero.Workflow.Shared.TaskObserversState, global::Sungero.SmartProcessing.IVerificationTaskObserversState
  {
    public VerificationTaskObserversState(global::Sungero.SmartProcessing.IVerificationTaskObservers entity) : base(entity) { }

    public new global::Sungero.SmartProcessing.IVerificationTaskObserversPropertyStates Properties
    {
      get { return (global::Sungero.SmartProcessing.IVerificationTaskObserversPropertyStates)base.Properties; }
    }

    protected override global::Sungero.Domain.Shared.IEntityPropertyStates CreatePropertyStates(global::Sungero.Domain.Shared.IEntity entity)
    {
      return new global::Sungero.SmartProcessing.Shared.VerificationTaskObserversPropertyStates(entity);
    }


  }


  public class VerificationTaskObserversPropertyStates : 
    global::Sungero.Workflow.Shared.TaskObserversPropertyStates, global::Sungero.SmartProcessing.IVerificationTaskObserversPropertyStates
  {
            public new global::Sungero.Domain.Shared.IPropertyState<global::Sungero.SmartProcessing.IVerificationTask> Task
            {
              get { return (global::Sungero.Domain.Shared.IPropertyState<global::Sungero.SmartProcessing.IVerificationTask>)base.Task; }
            }

            protected override global::Sungero.Domain.Shared.IPropertyState<global::Sungero.Workflow.ITask> InternalTask
            {
              get { return this.GetPropertyState<global::Sungero.SmartProcessing.IVerificationTask>("Task"); }
            }


    protected internal VerificationTaskObserversPropertyStates(global::Sungero.Domain.Shared.IEntity entity) : base(entity) { }
  }

  public class VerificationTaskObserversCollectionPropertyState<T> :
    global::Sungero.Workflow.Shared.TaskObserversCollectionPropertyState<T>, global::Sungero.SmartProcessing.IVerificationTaskObserversCollectionPropertyState<T>
    where T : global::Sungero.SmartProcessing.IVerificationTaskObservers
  {
    public new global::Sungero.SmartProcessing.IVerificationTaskObserversCollectionPropertyStates Properties
    {
      get { return (global::Sungero.SmartProcessing.IVerificationTaskObserversCollectionPropertyStates)base.Properties; }
    }

    protected override global::Sungero.Domain.Shared.IChildEntityCollectionPropertyStates CreatePropertyStates()
    {
      return new global::Sungero.SmartProcessing.Shared.VerificationTaskObserversCollectionPropertyStates(this.ChildEntityMetadata);
    }

    protected internal VerificationTaskObserversCollectionPropertyState(global::Sungero.Domain.Shared.IEntity entity, string propertyName) : base(entity, propertyName) { }
  }

  public class VerificationTaskObserversCollectionPropertyStates :
    global::Sungero.Workflow.Shared.TaskObserversCollectionPropertyStates, global::Sungero.SmartProcessing.IVerificationTaskObserversCollectionPropertyStates
  {

    protected internal VerificationTaskObserversCollectionPropertyStates(global::Sungero.Metadata.EntityMetadata childEntityMetadata) : base(childEntityMetadata) { }
  }
}

// ==================================================================
// VerificationTaskObserversEventArgs.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.SmartProcessing.Shared
{  
}

// ==================================================================
// VerificationTaskObserversInfo.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.SmartProcessing.Shared
{
  public class VerificationTaskObserversInfo : 
    global::Sungero.Workflow.Shared.TaskObserversInfo, global::Sungero.SmartProcessing.IVerificationTaskObserversInfo
  {
    public VerificationTaskObserversInfo(global::System.Type entityType) : base(entityType) { }

    public new global::Sungero.SmartProcessing.IVerificationTaskObserversPropertiesInfo Properties
    {
      get { return (global::Sungero.SmartProcessing.IVerificationTaskObserversPropertiesInfo)base.Properties; }
    }

    protected override global::Sungero.Domain.Shared.IEntityPropertiesInfo CreateEntityPropertiesInfo(global::System.Type entityType)
    {
      return new global::Sungero.SmartProcessing.Shared.VerificationTaskObserversPropertiesInfo(entityType);
    }

  }

  public class VerificationTaskObserversPropertiesInfo : 
    global::Sungero.Workflow.Shared.TaskObserversPropertiesInfo, global::Sungero.SmartProcessing.IVerificationTaskObserversPropertiesInfo
  {
        public new global::Sungero.Domain.Shared.INavigationPropertyInfo<global::Sungero.SmartProcessing.IVerificationTaskInfo, global::Sungero.SmartProcessing.IVerificationTask> Task
        {
          get
          {
             var propertyMetadata = this.GetPropertyMetadata<global::Sungero.Metadata.NavigationPropertyMetadata>("Task");
             return new global::Sungero.Domain.Shared.NavigationPropertyInfo<global::Sungero.SmartProcessing.IVerificationTaskInfo, global::Sungero.SmartProcessing.IVerificationTask>(propertyMetadata);
          }
        }


    protected internal VerificationTaskObserversPropertiesInfo(global::System.Type entityType) : base(entityType) { }
  }

}
