
// ==================================================================
// ContractCategoryDocumentKinds.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Contracts.Server
{
  public class ContractCategoryDocumentKindsFilterForDocumentKind<TQueryEntity, TSourceEntity, TRootEntity>
    : global::Sungero.Docflow.Server.DocumentGroupBaseDocumentKindsFilterForDocumentKind<TQueryEntity, TSourceEntity, TRootEntity>
    where TQueryEntity : class, global::Sungero.Docflow.IDocumentKind
    where TSourceEntity : class, global::Sungero.Contracts.IContractCategoryDocumentKinds
    where TRootEntity : class, global::Sungero.Contracts.IContractCategory
  {
    protected override global::System.Linq.IQueryable<TQueryEntity> ApplyAppliedFilter(global::System.Linq.IQueryable<TQueryEntity> query, TSourceEntity sourceEntity, TRootEntity rootEntity)
    {
      var args = new global::Sungero.Domain.PropertyFilteringEventArgs(sourceEntity);
      var result = new global::Sungero.Contracts.ContractCategoryDocumentKindsDocumentKindPropertyFilteringServerHandler<TQueryEntity>(sourceEntity, rootEntity).DocumentKindsDocumentKindFiltering(query, args);
      if (args.DisableUiFiltering)
        global::Sungero.Domain.UiFilteringEventManagementScope.DisableEvent<TQueryEntity>();
      return result;
    }

    public ContractCategoryDocumentKindsFilterForDocumentKind(string propertyName)
      : base(propertyName)
    {
    }
  }



  [global::Sungero.Domain.PropertyFilter(typeof(global::Sungero.Contracts.Server.ContractCategoryDocumentKindsFilterForDocumentKind<global::Sungero.Docflow.IDocumentKind, global::Sungero.Contracts.IContractCategoryDocumentKinds, global::Sungero.Contracts.IContractCategory>), "DocumentKind")]


  public class ContractCategoryDocumentKinds :
    global::Sungero.Docflow.Server.DocumentGroupBaseDocumentKinds, global::Sungero.Contracts.IContractCategoryDocumentKinds
  {
    public static new readonly global::System.Guid ClassTypeGuid = global::System.Guid.Parse("a9ad8c06-3d46-4302-be22-43b3b909f718");

    public override global::System.Guid TypeGuid
    {
      get { return global::Sungero.Contracts.Server.ContractCategoryDocumentKinds.ClassTypeGuid; }
    }

    public override string TypeName
    {
      get { return "Sungero.Contracts.IContractCategoryDocumentKinds, Sungero.Domain.Interfaces"; }
    }

    public new virtual global::Sungero.Contracts.IContractCategoryDocumentKindsState State
    {
      get { return (global::Sungero.Contracts.IContractCategoryDocumentKindsState)base.State; }
    }

    protected override global::Sungero.Domain.Shared.IEntityState CreateState()
    {
      return new global::Sungero.Contracts.Shared.ContractCategoryDocumentKindsState(this);
    }

    public new virtual global::Sungero.Contracts.IContractCategoryDocumentKindsInfo Info
    {
      get { return (global::Sungero.Contracts.IContractCategoryDocumentKindsInfo)base.Info; }
    }










    #region Framework events



    #endregion


    public ContractCategoryDocumentKinds()
    {
    }

  }
}

// ==================================================================
// ContractCategoryDocumentKindsHandlers.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Contracts
{
  public partial class ContractCategoryDocumentKindsDocumentKindPropertyFilteringServerHandler<T>
    : global::Sungero.Docflow.DocumentGroupBaseDocumentKindsDocumentKindPropertyFilteringServerHandler<T>
    where T : class, global::Sungero.Docflow.IDocumentKind
  {
    private global::Sungero.Contracts.IContractCategoryDocumentKinds _obj
    {
      get { return (global::Sungero.Contracts.IContractCategoryDocumentKinds)this.Entity; }
    }

    private global::Sungero.Contracts.IContractCategory _root
    {
      get { return (global::Sungero.Contracts.IContractCategory)this.Root; }
    }

    public ContractCategoryDocumentKindsDocumentKindPropertyFilteringServerHandler(global::Sungero.Contracts.IContractCategoryDocumentKinds entity, global::Sungero.Contracts.IContractCategory root)
      : base(entity, root)
    {
    }
  }



}

// ==================================================================
// ContractCategoryDocumentKindsEventArgs.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Contracts.Server
{
}
