
// ==================================================================
// SmartProcessingSetting.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Docflow.Client
{
  public class SmartProcessingSetting :
    global::Sungero.CoreEntities.Client.DatabookEntry, global::Sungero.Docflow.ISmartProcessingSetting
  {
    #region Fields and properties

    public static new readonly global::System.Guid ClassTypeGuid = global::System.Guid.Parse("22610ea3-dd6d-4aee-b7cc-0ba6cd179eb1");

    public override global::System.Guid TypeGuid
    {
      get { return global::Sungero.Docflow.Client.SmartProcessingSetting.ClassTypeGuid; }
    }

    public override string TypeName
    {
      get { return "Sungero.Docflow.ISmartProcessingSetting, Sungero.Domain.Interfaces"; }
    }

      public override string DisplayValue
      {
        get { return this.Name; }
        set { this.Name = value; }
      }

      public override string DisplayPropertyName
      {
        get { return "Name"; }
      }


    public new global::Sungero.Docflow.ISmartProcessingSettingState State
    {
      get
      {
        return (global::Sungero.Docflow.ISmartProcessingSettingState)base.State;
      }
    }

    protected override global::Sungero.Domain.Shared.IEntityState CreateState()
    {
      return new global::Sungero.Docflow.Shared.SmartProcessingSettingState(this);
    }

    public new global::Sungero.Docflow.ISmartProcessingSettingInfo Info
    {
      get
      {
        return (global::Sungero.Docflow.ISmartProcessingSettingInfo)base.Info;
      }
    }

    public new global::Sungero.Docflow.ISmartProcessingSettingAccessRights AccessRights
    {
      get
      {
        return (global::Sungero.Docflow.ISmartProcessingSettingAccessRights)base.AccessRights;
      }
    }

    protected override global::Sungero.Domain.Shared.IEntityAccessRights CreateAccessRights()
    {
      return new global::Sungero.Docflow.Client.SmartProcessingSettingAccessRights(this);
    }

        protected global::Sungero.Domain.Client.SimpleProperty<global::System.String> _Name;

        public virtual global::System.String Name
        {
          get { return this._Name.Value; }
          set { this._Name.Value = value; }
        }
        protected global::Sungero.Domain.Client.SimpleProperty<global::System.String> _ArioUrl;

        public virtual global::System.String ArioUrl
        {
          get { return this._ArioUrl.Value; }
          set { this._ArioUrl.Value = value; }
        }
        protected global::Sungero.Domain.Client.SimpleProperty<global::System.Int32?> _LowerConfidenceLimit;

        public virtual global::System.Int32? LowerConfidenceLimit
        {
          get { return this._LowerConfidenceLimit.Value; }
          set { this._LowerConfidenceLimit.Value = value; }
        }
        protected global::Sungero.Domain.Client.SimpleProperty<global::System.Int32?> _UpperConfidenceLimit;

        public virtual global::System.Int32? UpperConfidenceLimit
        {
          get { return this._UpperConfidenceLimit.Value; }
          set { this._UpperConfidenceLimit.Value = value; }
        }
        protected global::Sungero.Domain.Client.SimpleProperty<global::System.String> _TypeClassifierName;

        public virtual global::System.String TypeClassifierName
        {
          get { return this._TypeClassifierName.Value; }
          set { this._TypeClassifierName.Value = value; }
        }
        protected global::Sungero.Domain.Client.SimpleProperty<global::System.Int32?> _TypeClassifierId;

        public virtual global::System.Int32? TypeClassifierId
        {
          get { return this._TypeClassifierId.Value; }
          set { this._TypeClassifierId.Value = value; }
        }
        protected global::Sungero.Domain.Client.SimpleProperty<global::System.String> _FirstPageClassifierName;

        public virtual global::System.String FirstPageClassifierName
        {
          get { return this._FirstPageClassifierName.Value; }
          set { this._FirstPageClassifierName.Value = value; }
        }
        protected global::Sungero.Domain.Client.SimpleProperty<global::System.Int32?> _FirstPageClassifierId;

        public virtual global::System.Int32? FirstPageClassifierId
        {
          get { return this._FirstPageClassifierId.Value; }
          set { this._FirstPageClassifierId.Value = value; }
        }







          protected global::Sungero.Domain.Client.IListProperty<global::Sungero.Docflow.ISmartProcessingSettingCaptureSources> _CaptureSources;

          virtual public global::Sungero.Domain.Shared.IChildEntityCollection<global::Sungero.Docflow.ISmartProcessingSettingCaptureSources> CaptureSources
          {
            get { return this._CaptureSources.Value; }
          }


          protected global::Sungero.Domain.Client.IListProperty<global::Sungero.Docflow.ISmartProcessingSettingProcessingRules> _ProcessingRules;

          virtual public global::Sungero.Domain.Shared.IChildEntityCollection<global::Sungero.Docflow.ISmartProcessingSettingProcessingRules> ProcessingRules
          {
            get { return this._ProcessingRules.Value; }
          }


          protected global::Sungero.Domain.Client.IListProperty<global::Sungero.Docflow.ISmartProcessingSettingAdditionalClassifiers> _AdditionalClassifiers;

          virtual public global::Sungero.Domain.Shared.IChildEntityCollection<global::Sungero.Docflow.ISmartProcessingSettingAdditionalClassifiers> AdditionalClassifiers
          {
            get { return this._AdditionalClassifiers.Value; }
          }




      protected global::Sungero.Domain.Client.TextProperty _LimitsDescription;

      [global::Sungero.Domain.Shared.DoNotSavePreviousValue]
      public virtual System.String LimitsDescription
      {
        get { return this._LimitsDescription.Value; }
        set { this._LimitsDescription.Value = value; }
      }



    private object _CaptureSourcesActionsHandlers;

    public object CaptureSourcesActionsHandlers
    {
      get
      {
        if (this._CaptureSourcesActionsHandlers == null)
          this._CaptureSourcesActionsHandlers = this.CreateCaptureSourcesActionsHandlers();
        return this._CaptureSourcesActionsHandlers;
      }
    }

    private object _CaptureSourcesCollectionActionsHandlers;

    public object CaptureSourcesCollectionActionsHandlers
    {
      get
      {
        if (this._CaptureSourcesCollectionActionsHandlers == null)
          this._CaptureSourcesCollectionActionsHandlers = this.CreateCaptureSourcesCollectionActionsHandlers();
        return this._CaptureSourcesCollectionActionsHandlers;
      }
    }
    private object _ProcessingRulesActionsHandlers;

    public object ProcessingRulesActionsHandlers
    {
      get
      {
        if (this._ProcessingRulesActionsHandlers == null)
          this._ProcessingRulesActionsHandlers = this.CreateProcessingRulesActionsHandlers();
        return this._ProcessingRulesActionsHandlers;
      }
    }

    private object _ProcessingRulesCollectionActionsHandlers;

    public object ProcessingRulesCollectionActionsHandlers
    {
      get
      {
        if (this._ProcessingRulesCollectionActionsHandlers == null)
          this._ProcessingRulesCollectionActionsHandlers = this.CreateProcessingRulesCollectionActionsHandlers();
        return this._ProcessingRulesCollectionActionsHandlers;
      }
    }
    private object _AdditionalClassifiersActionsHandlers;

    public object AdditionalClassifiersActionsHandlers
    {
      get
      {
        if (this._AdditionalClassifiersActionsHandlers == null)
          this._AdditionalClassifiersActionsHandlers = this.CreateAdditionalClassifiersActionsHandlers();
        return this._AdditionalClassifiersActionsHandlers;
      }
    }

    private object _AdditionalClassifiersCollectionActionsHandlers;

    public object AdditionalClassifiersCollectionActionsHandlers
    {
      get
      {
        if (this._AdditionalClassifiersCollectionActionsHandlers == null)
          this._AdditionalClassifiersCollectionActionsHandlers = this.CreateAdditionalClassifiersCollectionActionsHandlers();
        return this._AdditionalClassifiersCollectionActionsHandlers;
      }
    }

    #endregion

    #region Methods

    protected override object CreateActionsHandlers()
    {
      return new global::Sungero.Docflow.Client.SmartProcessingSettingActions(this);
    }

    protected override object CreateCollectionActionsHandlers()
    {
      return new global::Sungero.Docflow.Client.SmartProcessingSettingCollectionActions();
    }

    protected override object CreateAnyChildEntityActionsHandlers()
    {
      return new global::Sungero.Docflow.Client.SmartProcessingSettingAnyChildEntityActions();
    }

    protected override object CreateAnyChildEntityCollectionActionsHandlers()
    {
      return new global::Sungero.Docflow.Client.SmartProcessingSettingAnyChildEntityCollectionActions();
    }

    protected object CreateCaptureSourcesActionsHandlers()
    {
      return null;
    }

    protected object CreateCaptureSourcesCollectionActionsHandlers()
    {
      return null;
    }
    protected object CreateProcessingRulesActionsHandlers()
    {
      return null;
    }

    protected object CreateProcessingRulesCollectionActionsHandlers()
    {
      return null;
    }
    protected object CreateAdditionalClassifiersActionsHandlers()
    {
      return null;
    }

    protected object CreateAdditionalClassifiersCollectionActionsHandlers()
    {
      return null;
    }


    protected override global::Sungero.Domain.Client.EntityFunctions CreateClientFunctions()
    {
      return new global::Sungero.Docflow.Client.SmartProcessingSettingFunctions(this);
    }

    protected override global::Sungero.Domain.Shared.EntityFunctions CreateSharedFunctions()
    {
      return new global::Sungero.Docflow.Shared.SmartProcessingSettingFunctions(this);
    }
    protected override object CreateHandlers() {
      return new global::Sungero.Docflow.SmartProcessingSettingClientHandlers(this);
    }
    protected override object CreateSharedHandlers() {
      return new global::Sungero.Docflow.SmartProcessingSettingSharedHandlers(this);
    }

    #endregion

    #region Framework events

    protected void NameChangedHandler()
    {
      var args = new global::Sungero.Domain.Shared.StringPropertyChangedEventArgs(this.State.Properties.Name, this.Name, this);
     ((global::Sungero.Docflow.SmartProcessingSettingSharedHandlers)this.SharedHandlers).NameChanged(args);
    }

    protected void ArioUrlChangedHandler()
    {
      var args = new global::Sungero.Domain.Shared.StringPropertyChangedEventArgs(this.State.Properties.ArioUrl, this.ArioUrl, this);
     ((global::Sungero.Docflow.SmartProcessingSettingSharedHandlers)this.SharedHandlers).ArioUrlChanged(args);
    }

    protected void LowerConfidenceLimitChangedHandler()
    {
      var args = new global::Sungero.Domain.Shared.IntegerPropertyChangedEventArgs(this.State.Properties.LowerConfidenceLimit, this.LowerConfidenceLimit, this);
     ((global::Sungero.Docflow.SmartProcessingSettingSharedHandlers)this.SharedHandlers).LowerConfidenceLimitChanged(args);
    }

    protected void UpperConfidenceLimitChangedHandler()
    {
      var args = new global::Sungero.Domain.Shared.IntegerPropertyChangedEventArgs(this.State.Properties.UpperConfidenceLimit, this.UpperConfidenceLimit, this);
     ((global::Sungero.Docflow.SmartProcessingSettingSharedHandlers)this.SharedHandlers).UpperConfidenceLimitChanged(args);
    }

    protected void LimitsDescriptionChangedHandler()
    {
      var args = new global::Sungero.Domain.Shared.TextPropertyChangedEventArgs(this.State.Properties.LimitsDescription, this.LimitsDescription, this);
     ((global::Sungero.Docflow.SmartProcessingSettingSharedHandlers)this.SharedHandlers).LimitsDescriptionChanged(args);
    }

    protected void TypeClassifierNameChangedHandler()
    {
      var args = new global::Sungero.Domain.Shared.StringPropertyChangedEventArgs(this.State.Properties.TypeClassifierName, this.TypeClassifierName, this);
     ((global::Sungero.Docflow.SmartProcessingSettingSharedHandlers)this.SharedHandlers).TypeClassifierNameChanged(args);
    }

    protected void TypeClassifierIdChangedHandler()
    {
      var args = new global::Sungero.Domain.Shared.IntegerPropertyChangedEventArgs(this.State.Properties.TypeClassifierId, this.TypeClassifierId, this);
     ((global::Sungero.Docflow.SmartProcessingSettingSharedHandlers)this.SharedHandlers).TypeClassifierIdChanged(args);
    }

    protected void FirstPageClassifierNameChangedHandler()
    {
      var args = new global::Sungero.Domain.Shared.StringPropertyChangedEventArgs(this.State.Properties.FirstPageClassifierName, this.FirstPageClassifierName, this);
     ((global::Sungero.Docflow.SmartProcessingSettingSharedHandlers)this.SharedHandlers).FirstPageClassifierNameChanged(args);
    }

    protected void FirstPageClassifierIdChangedHandler()
    {
      var args = new global::Sungero.Domain.Shared.IntegerPropertyChangedEventArgs(this.State.Properties.FirstPageClassifierId, this.FirstPageClassifierId, this);
     ((global::Sungero.Docflow.SmartProcessingSettingSharedHandlers)this.SharedHandlers).FirstPageClassifierIdChanged(args);
    }

    protected void CaptureSourcesChangedHandler()
    {
      var args = new global::Sungero.Domain.Shared.CollectionPropertyChangedEventArgs(this);
     ((global::Sungero.Docflow.SmartProcessingSettingSharedHandlers)this.SharedHandlers).CaptureSourcesChanged(args);
    }

    protected void ProcessingRulesChangedHandler()
    {
      var args = new global::Sungero.Domain.Shared.CollectionPropertyChangedEventArgs(this);
     ((global::Sungero.Docflow.SmartProcessingSettingSharedHandlers)this.SharedHandlers).ProcessingRulesChanged(args);
    }

    protected void AdditionalClassifiersChangedHandler()
    {
      var args = new global::Sungero.Domain.Shared.CollectionPropertyChangedEventArgs(this);
     ((global::Sungero.Docflow.SmartProcessingSettingSharedHandlers)this.SharedHandlers).AdditionalClassifiersChanged(args);
    }



    protected virtual global::Sungero.Docflow.SmartProcessingSettingCaptureSourcesSharedCollectionHandlers CreateCaptureSourcesAddedHandler(global::Sungero.Domain.Shared.ChildEntityAddedEventArgs<global::Sungero.Domain.Shared.IChildEntity> e)
    {
      return new global::Sungero.Docflow.SmartProcessingSettingCaptureSourcesSharedCollectionHandlers(this, e.Value, null, e.Source);
    }

    protected virtual global::Sungero.Docflow.SmartProcessingSettingCaptureSourcesSharedCollectionHandlers CreateCaptureSourcesDeletedHandler(global::Sungero.Domain.Shared.ChildEntityDeletedEventArgs<global::Sungero.Domain.Shared.IChildEntity> e)
    {
      return new global::Sungero.Docflow.SmartProcessingSettingCaptureSourcesSharedCollectionHandlers(this, null, e.Value, null);
    }

    protected virtual void CaptureSourcesAddedHandler(object sender, global::Sungero.Domain.Shared.ChildEntityAddedEventArgs<global::Sungero.Domain.Shared.IChildEntity> e)
    {  
      var collectionHandlers = this.CreateCaptureSourcesAddedHandler(e);
      if (collectionHandlers != null)
      {
        var args = new global::Sungero.Domain.Shared.CollectionPropertyAddedEventArgs(this);
        collectionHandlers.CaptureSourcesAdded(args);
      }
    }

    protected virtual void CaptureSourcesDeletedHandler(object sender, global::Sungero.Domain.Shared.ChildEntityDeletedEventArgs<global::Sungero.Domain.Shared.IChildEntity> e)
    {  
      var collectionHandlers = this.CreateCaptureSourcesDeletedHandler(e);
      if (collectionHandlers != null)
      {
        var args = new global::Sungero.Domain.Shared.CollectionPropertyDeletedEventArgs(this);
        collectionHandlers.CaptureSourcesDeleted(args);
      }
    }


    protected virtual global::Sungero.Docflow.SmartProcessingSettingProcessingRulesSharedCollectionHandlers CreateProcessingRulesAddedHandler(global::Sungero.Domain.Shared.ChildEntityAddedEventArgs<global::Sungero.Domain.Shared.IChildEntity> e)
    {
      return new global::Sungero.Docflow.SmartProcessingSettingProcessingRulesSharedCollectionHandlers(this, e.Value, null, e.Source);
    }

    protected virtual global::Sungero.Docflow.SmartProcessingSettingProcessingRulesSharedCollectionHandlers CreateProcessingRulesDeletedHandler(global::Sungero.Domain.Shared.ChildEntityDeletedEventArgs<global::Sungero.Domain.Shared.IChildEntity> e)
    {
      return new global::Sungero.Docflow.SmartProcessingSettingProcessingRulesSharedCollectionHandlers(this, null, e.Value, null);
    }

    protected virtual void ProcessingRulesAddedHandler(object sender, global::Sungero.Domain.Shared.ChildEntityAddedEventArgs<global::Sungero.Domain.Shared.IChildEntity> e)
    {  
      var collectionHandlers = this.CreateProcessingRulesAddedHandler(e);
      if (collectionHandlers != null)
      {
        var args = new global::Sungero.Domain.Shared.CollectionPropertyAddedEventArgs(this);
        collectionHandlers.ProcessingRulesAdded(args);
      }
    }

    protected virtual void ProcessingRulesDeletedHandler(object sender, global::Sungero.Domain.Shared.ChildEntityDeletedEventArgs<global::Sungero.Domain.Shared.IChildEntity> e)
    {  
      var collectionHandlers = this.CreateProcessingRulesDeletedHandler(e);
      if (collectionHandlers != null)
      {
        var args = new global::Sungero.Domain.Shared.CollectionPropertyDeletedEventArgs(this);
        collectionHandlers.ProcessingRulesDeleted(args);
      }
    }


    protected virtual global::Sungero.Docflow.SmartProcessingSettingAdditionalClassifiersSharedCollectionHandlers CreateAdditionalClassifiersAddedHandler(global::Sungero.Domain.Shared.ChildEntityAddedEventArgs<global::Sungero.Domain.Shared.IChildEntity> e)
    {
      return new global::Sungero.Docflow.SmartProcessingSettingAdditionalClassifiersSharedCollectionHandlers(this, e.Value, null, e.Source);
    }

    protected virtual global::Sungero.Docflow.SmartProcessingSettingAdditionalClassifiersSharedCollectionHandlers CreateAdditionalClassifiersDeletedHandler(global::Sungero.Domain.Shared.ChildEntityDeletedEventArgs<global::Sungero.Domain.Shared.IChildEntity> e)
    {
      return new global::Sungero.Docflow.SmartProcessingSettingAdditionalClassifiersSharedCollectionHandlers(this, null, e.Value, null);
    }

    protected virtual void AdditionalClassifiersAddedHandler(object sender, global::Sungero.Domain.Shared.ChildEntityAddedEventArgs<global::Sungero.Domain.Shared.IChildEntity> e)
    {  
      var collectionHandlers = this.CreateAdditionalClassifiersAddedHandler(e);
      if (collectionHandlers != null)
      {
        var args = new global::Sungero.Domain.Shared.CollectionPropertyAddedEventArgs(this);
        collectionHandlers.AdditionalClassifiersAdded(args);
      }
    }

    protected virtual void AdditionalClassifiersDeletedHandler(object sender, global::Sungero.Domain.Shared.ChildEntityDeletedEventArgs<global::Sungero.Domain.Shared.IChildEntity> e)
    {  
      var collectionHandlers = this.CreateAdditionalClassifiersDeletedHandler(e);
      if (collectionHandlers != null)
      {
        var args = new global::Sungero.Domain.Shared.CollectionPropertyDeletedEventArgs(this);
        collectionHandlers.AdditionalClassifiersDeleted(args);
      }
    }


  protected global::System.String NameValueInputHandler(global::System.String value)
  {
    var args = new global::Sungero.Presentation.StringValueInputEventArgs(this.Name, value, this, this.Info.Properties.Name);
    ((global::Sungero.Docflow.SmartProcessingSettingClientHandlers)this.Handlers).NameValueInput(args);
    return args.NewValue;
  }

  protected global::System.String ArioUrlValueInputHandler(global::System.String value)
  {
    var args = new global::Sungero.Presentation.StringValueInputEventArgs(this.ArioUrl, value, this, this.Info.Properties.ArioUrl);
    ((global::Sungero.Docflow.SmartProcessingSettingClientHandlers)this.Handlers).ArioUrlValueInput(args);
    return args.NewValue;
  }

  protected global::System.Int32? LowerConfidenceLimitValueInputHandler(global::System.Int32? value)
  {
    var args = new global::Sungero.Presentation.IntegerValueInputEventArgs(this.LowerConfidenceLimit, value, this, this.Info.Properties.LowerConfidenceLimit);
    ((global::Sungero.Docflow.SmartProcessingSettingClientHandlers)this.Handlers).LowerConfidenceLimitValueInput(args);
    return args.NewValue;
  }

  protected global::System.Int32? UpperConfidenceLimitValueInputHandler(global::System.Int32? value)
  {
    var args = new global::Sungero.Presentation.IntegerValueInputEventArgs(this.UpperConfidenceLimit, value, this, this.Info.Properties.UpperConfidenceLimit);
    ((global::Sungero.Docflow.SmartProcessingSettingClientHandlers)this.Handlers).UpperConfidenceLimitValueInput(args);
    return args.NewValue;
  }

  protected global::System.String LimitsDescriptionValueInputHandler(global::System.String value)
  {
    var args = new global::Sungero.Presentation.TextValueInputEventArgs(this.LimitsDescription, value, this, this.Info.Properties.LimitsDescription);
    ((global::Sungero.Docflow.SmartProcessingSettingClientHandlers)this.Handlers).LimitsDescriptionValueInput(args);
    return args.NewValue;
  }

  protected global::System.String TypeClassifierNameValueInputHandler(global::System.String value)
  {
    var args = new global::Sungero.Presentation.StringValueInputEventArgs(this.TypeClassifierName, value, this, this.Info.Properties.TypeClassifierName);
    ((global::Sungero.Docflow.SmartProcessingSettingClientHandlers)this.Handlers).TypeClassifierNameValueInput(args);
    return args.NewValue;
  }

  protected global::System.Int32? TypeClassifierIdValueInputHandler(global::System.Int32? value)
  {
    var args = new global::Sungero.Presentation.IntegerValueInputEventArgs(this.TypeClassifierId, value, this, this.Info.Properties.TypeClassifierId);
    ((global::Sungero.Docflow.SmartProcessingSettingClientHandlers)this.Handlers).TypeClassifierIdValueInput(args);
    return args.NewValue;
  }

  protected global::System.String FirstPageClassifierNameValueInputHandler(global::System.String value)
  {
    var args = new global::Sungero.Presentation.StringValueInputEventArgs(this.FirstPageClassifierName, value, this, this.Info.Properties.FirstPageClassifierName);
    ((global::Sungero.Docflow.SmartProcessingSettingClientHandlers)this.Handlers).FirstPageClassifierNameValueInput(args);
    return args.NewValue;
  }

  protected global::System.Int32? FirstPageClassifierIdValueInputHandler(global::System.Int32? value)
  {
    var args = new global::Sungero.Presentation.IntegerValueInputEventArgs(this.FirstPageClassifierId, value, this, this.Info.Properties.FirstPageClassifierId);
    ((global::Sungero.Docflow.SmartProcessingSettingClientHandlers)this.Handlers).FirstPageClassifierIdValueInput(args);
    return args.NewValue;
  }






    #endregion

    #region Constructors


            protected virtual void InitCaptureSourcesCollectionProperty()
            {
              this._CaptureSources = new global::Sungero.Domain.Client.ListProperty<global::Sungero.Docflow.ISmartProcessingSettingCaptureSources>("CaptureSources", this);
              this._CaptureSources.ValueChanged += (sender, e) => { this.CaptureSourcesChangedHandler(); };
              this.AddProperty((global::Sungero.Domain.Client.IProperty)this._CaptureSources);
              this.SetCaptureSourcesEventHandlers();
            }

            protected void SetCaptureSourcesEventHandlers()
            {
              this._CaptureSources.ChildEntityAdded += this.CaptureSourcesAddedHandler;
              this._CaptureSources.ChildEntityDeleted += this.CaptureSourcesDeletedHandler;
            }

            protected virtual void InitProcessingRulesCollectionProperty()
            {
              this._ProcessingRules = new global::Sungero.Domain.Client.ListProperty<global::Sungero.Docflow.ISmartProcessingSettingProcessingRules>("ProcessingRules", this);
              this._ProcessingRules.ValueChanged += (sender, e) => { this.ProcessingRulesChangedHandler(); };
              this.AddProperty((global::Sungero.Domain.Client.IProperty)this._ProcessingRules);
              this.SetProcessingRulesEventHandlers();
            }

            protected void SetProcessingRulesEventHandlers()
            {
              this._ProcessingRules.ChildEntityAdded += this.ProcessingRulesAddedHandler;
              this._ProcessingRules.ChildEntityDeleted += this.ProcessingRulesDeletedHandler;
            }

            protected virtual void InitAdditionalClassifiersCollectionProperty()
            {
              this._AdditionalClassifiers = new global::Sungero.Domain.Client.ListProperty<global::Sungero.Docflow.ISmartProcessingSettingAdditionalClassifiers>("AdditionalClassifiers", this);
              this._AdditionalClassifiers.ValueChanged += (sender, e) => { this.AdditionalClassifiersChangedHandler(); };
              this.AddProperty((global::Sungero.Domain.Client.IProperty)this._AdditionalClassifiers);
              this.SetAdditionalClassifiersEventHandlers();
            }

            protected void SetAdditionalClassifiersEventHandlers()
            {
              this._AdditionalClassifiers.ChildEntityAdded += this.AdditionalClassifiersAddedHandler;
              this._AdditionalClassifiers.ChildEntityDeleted += this.AdditionalClassifiersDeletedHandler;
            }


    public SmartProcessingSetting()
    {
            this._Name = new global::Sungero.Domain.Client.SimpleProperty<global::System.String>("Name", this);
            this._Name.ValueChanged += (sender, e) => { this.NameChangedHandler(); };
            this.AddProperty(this._Name);

            this._ArioUrl = new global::Sungero.Domain.Client.SimpleProperty<global::System.String>("ArioUrl", this);
            this._ArioUrl.ValueChanged += (sender, e) => { this.ArioUrlChangedHandler(); };
            this.AddProperty(this._ArioUrl);

            this._LowerConfidenceLimit = new global::Sungero.Domain.Client.SimpleProperty<global::System.Int32?>("LowerConfidenceLimit", this);
            this._LowerConfidenceLimit.ValueChanged += (sender, e) => { this.LowerConfidenceLimitChangedHandler(); };
            this.AddProperty(this._LowerConfidenceLimit);

            this._UpperConfidenceLimit = new global::Sungero.Domain.Client.SimpleProperty<global::System.Int32?>("UpperConfidenceLimit", this);
            this._UpperConfidenceLimit.ValueChanged += (sender, e) => { this.UpperConfidenceLimitChangedHandler(); };
            this.AddProperty(this._UpperConfidenceLimit);

            this._TypeClassifierName = new global::Sungero.Domain.Client.SimpleProperty<global::System.String>("TypeClassifierName", this);
            this._TypeClassifierName.ValueChanged += (sender, e) => { this.TypeClassifierNameChangedHandler(); };
            this.AddProperty(this._TypeClassifierName);

            this._TypeClassifierId = new global::Sungero.Domain.Client.SimpleProperty<global::System.Int32?>("TypeClassifierId", this);
            this._TypeClassifierId.ValueChanged += (sender, e) => { this.TypeClassifierIdChangedHandler(); };
            this.AddProperty(this._TypeClassifierId);

            this._FirstPageClassifierName = new global::Sungero.Domain.Client.SimpleProperty<global::System.String>("FirstPageClassifierName", this);
            this._FirstPageClassifierName.ValueChanged += (sender, e) => { this.FirstPageClassifierNameChangedHandler(); };
            this.AddProperty(this._FirstPageClassifierName);

            this._FirstPageClassifierId = new global::Sungero.Domain.Client.SimpleProperty<global::System.Int32?>("FirstPageClassifierId", this);
            this._FirstPageClassifierId.ValueChanged += (sender, e) => { this.FirstPageClassifierIdChangedHandler(); };
            this.AddProperty(this._FirstPageClassifierId);


            this.InitCaptureSourcesCollectionProperty();

            this.InitProcessingRulesCollectionProperty();

            this.InitAdditionalClassifiersCollectionProperty();


            this._LimitsDescription = new global::Sungero.Domain.Client.TextProperty("LimitsDescription", this);
            this._LimitsDescription.ValueChanged += (sender, e) => { this.LimitsDescriptionChangedHandler(); };
            this.AddProperty(this._LimitsDescription);






    }

    #endregion

  }
}

// ==================================================================
// SmartProcessingSettingPresenter.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Docflow.Client
{
  public class SmartProcessingSettingPresenter<T> :
    global::Sungero.Domain.Client.EntityPresenter<T>
    where T : class, global::Sungero.Docflow.ISmartProcessingSetting
  {
    #region Fields and properties

          private global::System.Windows.Input.ICommand _CheckConnectionCommand;

          public global::System.Windows.Input.ICommand CheckConnectionCommand
          {
            get
            {
              if (this._CheckConnectionCommand == null)
                  this._CheckConnectionCommand = new global::Sungero.Domain.Client.SingleEntityCommand<T>("CheckConnection", this, this.CheckConnection, this.CanCheckConnection) { IsEmptyParameterAllowed = true };
              return this._CheckConnectionCommand;
            }
          }
          private global::System.Windows.Input.ICommand _ForceSaveCommand;

          public global::System.Windows.Input.ICommand ForceSaveCommand
          {
            get
            {
              if (this._ForceSaveCommand == null)
                  this._ForceSaveCommand = new global::Sungero.Domain.Client.SingleEntityCommand<T>("ForceSave", this, this.ForceSave, this.CanForceSave) { IsEmptyParameterAllowed = true };
              return this._ForceSaveCommand;
            }
          }




    #endregion

    #region Methods

              private bool CanCheckConnection(T entity)
              {
                var args = new global::Sungero.Domain.Client.WpfCanExecuteActionArgs(global::Sungero.Domain.Shared.FormType.Card, entity, this);
                return ((Sungero.Docflow.Client.SmartProcessingSettingActions)(entity as Sungero.Docflow.Client.SmartProcessingSetting).ActionsHandlers).CanCheckConnection(args);
              }

              private void CheckConnection(T entity)
              {
                var args = new global::Sungero.Domain.Client.WpfExecuteActionArgs(global::Sungero.Domain.Shared.FormType.Card, entity, this, entity.Info.Actions.CheckConnection);
                ((Sungero.Docflow.Client.SmartProcessingSettingActions)(entity as Sungero.Docflow.Client.SmartProcessingSetting).ActionsHandlers).CheckConnection(args);
              }

              private bool CanForceSave(T entity)
              {
                var args = new global::Sungero.Domain.Client.WpfCanExecuteActionArgs(global::Sungero.Domain.Shared.FormType.Card, entity, this);
                return ((Sungero.Docflow.Client.SmartProcessingSettingActions)(entity as Sungero.Docflow.Client.SmartProcessingSetting).ActionsHandlers).CanForceSave(args);
              }

              private void ForceSave(T entity)
              {
                var args = new global::Sungero.Domain.Client.WpfExecuteActionArgs(global::Sungero.Domain.Shared.FormType.Card, entity, this, entity.Info.Actions.ForceSave);
                ((Sungero.Docflow.Client.SmartProcessingSettingActions)(entity as Sungero.Docflow.Client.SmartProcessingSetting).ActionsHandlers).ForceSave(args);
              }


    #endregion

    #region Framework events

    protected override void EntityPropertyChangedEventHandler(object sender, global::System.ComponentModel.PropertyChangedEventArgs e)
    {
      base.EntityPropertyChangedEventHandler(sender, e);
    }

    #endregion


                          protected global::Sungero.Domain.Client.IEntityCollectionPresenter _CaptureSourcesResponsibleCollectionPresenter;
                          public global::Sungero.Domain.Client.IEntityCollectionPresenter CaptureSourcesResponsibleCollectionPresenter
                          {
                  get { return this._CaptureSourcesResponsibleCollectionPresenter; }
                }



    #region Constructors

    private void Init()
    {

                          this._CaptureSourcesResponsibleCollectionPresenter = this.CreateCollectionPresenterForNavigationProperty<global::Sungero.CoreEntities.IRecipient>(global::System.Guid.Parse("9a910489-d37f-4c2d-a0f6-1da960f2f9c6"));
                        this._CaptureSourcesResponsibleCollectionPresenter
                        .Query = global::Sungero.Domain.Client.Session.GetValuesForNavigationPropertyWithoutSourceEntity<global::Sungero.CoreEntities.IRecipient>(() => this.Entity.Id, typeof(Sungero.Docflow.ISmartProcessingSettingCaptureSources), "Responsible");


    }

    public SmartProcessingSettingPresenter()
    {
      this.Init();
    }

    #endregion
  }
}

// ==================================================================
// SmartProcessingSettingCollectionPresenter.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Docflow.Client
{
  public class SmartProcessingSettingCollectionPresenter<T> : 
    global::Sungero.Domain.Client.EntityCollectionPresenter<T>
    where T: class, global::Sungero.Docflow.ISmartProcessingSetting
  {
    #region Actions



    #endregion

    #region Methods


    #endregion

    public SmartProcessingSettingCollectionPresenter(global::System.Linq.IQueryable<T> query, OnLookup onLookup)
      : base(query, onLookup)
    {
    }

    public SmartProcessingSettingCollectionPresenter(global::System.Linq.IQueryable<T> query)
      : this(query, null) { }

    public SmartProcessingSettingCollectionPresenter(OnLookup onLookup)
      : this(null, onLookup) { }

    public SmartProcessingSettingCollectionPresenter()
      : this(null, null) { }
  }
}

// ==================================================================
// SmartProcessingSettingRepositoryImplementer.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Docflow.Client
{ 
  public class SmartProcessingSettingRepositoryImplementer<T> : 
      global::Sungero.Domain.Client.RepositoryImplementer<T>,
      global::Sungero.Docflow.ISmartProcessingSettingRepositoryImplementer<T>
      where T : global::Sungero.Docflow.ISmartProcessingSetting
    {
       public new global::Sungero.Docflow.ISmartProcessingSettingAccessRights AccessRights
       {
          get { return (global::Sungero.Docflow.ISmartProcessingSettingAccessRights)base.AccessRights; }
       }

       public new global::Sungero.Docflow.ISmartProcessingSettingInfo Info
       {
          get { return (global::Sungero.Docflow.ISmartProcessingSettingInfo)base.Info; }
       }

       protected override global::Sungero.Domain.Shared.IEntityAccessRights CreateAccessRights()
       {
         return new global::Sungero.Docflow.Client.SmartProcessingSettingTypeAccessRights(typeof(T));
       }
    }
}

// ==================================================================
// SmartProcessingSettingAccessRights.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Docflow.Client
{
  public class SmartProcessingSettingAccessRights : 
    Sungero.CoreEntities.Client.DatabookEntryAccessRights, Sungero.Docflow.ISmartProcessingSettingAccessRights
  {

    public SmartProcessingSettingAccessRights(global::Sungero.Domain.Shared.IEntity entity) : base(entity)
    {
    }
  }

  public class SmartProcessingSettingTypeAccessRights : 
    Sungero.CoreEntities.Client.DatabookEntryTypeAccessRights, Sungero.Docflow.ISmartProcessingSettingAccessRights
  {

    public SmartProcessingSettingTypeAccessRights(global::System.Type entityType) : base(entityType)
    {
    }
  }
}
