
// ==================================================================
// CurrencyEventArgs.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Commons.Client
{ 
}

// ==================================================================
// CurrencyHandlers.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Commons
{

  public partial class CurrencyFilteringClientHandler
    : global::Sungero.Domain.EntityFilteringClientHandler
  {
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    protected global::Sungero.Commons.ICurrencyFilterState Filter { get; private set; }

    private global::Sungero.Commons.ICurrencyFilterState _filter
    {
      get
      {
        return this.Filter;
      }
    }

    public CurrencyFilteringClientHandler(global::Sungero.Commons.ICurrencyFilterState filter)
    : base()
    {
      this.Filter = filter;
    }

    protected CurrencyFilteringClientHandler()
    {
    }

    public override void ValidateFilterPanel(global::Sungero.Domain.Client.ValidateFilterPanelEventArgs e)
    {
    }
  }


  public partial class CurrencyClientHandlers : global::Sungero.CoreEntities.DatabookEntryClientHandlers
  {
    private global::Sungero.Commons.ICurrency _obj
    {
      get { return (global::Sungero.Commons.ICurrency)this.Entity; }
    }

    public virtual void NameValueInput(global::Sungero.Presentation.StringValueInputEventArgs e) { }


    public virtual void AlphaCodeValueInput(global::Sungero.Presentation.StringValueInputEventArgs e) { }


    public virtual void ShortNameValueInput(global::Sungero.Presentation.StringValueInputEventArgs e) { }


    public virtual void FractionNameValueInput(global::Sungero.Presentation.StringValueInputEventArgs e) { }


    public virtual void IsDefaultValueInput(global::Sungero.Presentation.BooleanValueInputEventArgs e) { }



    public CurrencyClientHandlers(global::Sungero.Commons.ICurrency entity) : base(entity)
    {
    }
  }

}

// ==================================================================
// CurrencyClientFunctions.g.cs
// ==================================================================

namespace Sungero.Commons.Client
{
  public partial class CurrencyFunctions : global::Sungero.CoreEntities.Client.DatabookEntryFunctions
  {
    private global::Sungero.Commons.ICurrency _obj
    {
      get { return (global::Sungero.Commons.ICurrency)this.Entity; }
    }

    public CurrencyFunctions(global::Sungero.Commons.ICurrency entity) : base(entity) { }
  }
}

// ==================================================================
// CurrencyFunctions.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Commons.Functions
{
  internal static class Currency
  {
    /// <redirect project="Sungero.Commons.Shared" type="Sungero.Commons.Shared.CurrencyFunctions" />
    internal static  global::System.Boolean HaveDuplicates(global::Sungero.Commons.ICurrency currency)
    {
      var functions = (global::Sungero.Commons.Shared.CurrencyFunctions)((global::Sungero.Domain.Shared.IEntityFunctions)currency).FunctionsContainer.SharedFunctions;
      return functions.HaveDuplicates();
    }
    /// <redirect project="Sungero.Commons.Shared" type="Sungero.Commons.Shared.CurrencyFunctions" />
    internal static  global::System.String ValidateNumericCode(global::System.String numericCode)
    {
      return global::Sungero.Commons.Shared.CurrencyFunctions.ValidateNumericCode(numericCode);
    }

    internal static class Remote
    {
      /// <redirect project="Sungero.Commons.Server" type="Sungero.Commons.Server.CurrencyFunctions" />
      internal static  global::Sungero.Commons.ICurrency GetDefaultCurrency()
      {
        return global::Sungero.Domain.Shared.RemoteFunctionExecutor.ExecuteWithResult<global::Sungero.Commons.ICurrency>(
          global::System.Guid.Parse("ffc2629f-dc30-4106-a3ce-c402ae7d32b9"),
          "GetDefaultCurrency()"
      );
      }
      /// <redirect project="Sungero.Commons.Server" type="Sungero.Commons.Server.CurrencyFunctions" />
      internal static  global::System.Linq.IQueryable<global::Sungero.Commons.ICurrency> GetDuplicates(global::Sungero.Commons.ICurrency currency)
      {
        return global::Sungero.Domain.Shared.RemoteFunctionExecutor.ExecuteWithResult<global::System.Linq.IQueryable<global::Sungero.Commons.ICurrency>>(
          global::System.Guid.Parse("ffc2629f-dc30-4106-a3ce-c402ae7d32b9"),
          "GetDuplicates(global::Sungero.Commons.ICurrency)"
          , currency);
      }

    }
  }
}

// ==================================================================
// CurrencyClientPublicFunctions.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Commons.Client
{
  public class CurrencyClientPublicFunctions : global::Sungero.Commons.Client.ICurrencyClientPublicFunctions
  {
  }
}

// ==================================================================
// CurrencyActions.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Commons.Client
{
  public partial class CurrencyActions : global::Sungero.CoreEntities.Client.DatabookEntryActions
  {
    private global::Sungero.Commons.ICurrency _obj { get { return (global::Sungero.Commons.ICurrency)this.Entity; } }
    public CurrencyActions(global::Sungero.Commons.ICurrency entity) : base(entity) { }
  }

  public partial class CurrencyCollectionActions : global::Sungero.CoreEntities.Client.DatabookEntryCollectionActions
  {
    private global::System.Collections.Generic.IEnumerable<global::Sungero.Commons.ICurrency> _objs
    { 
      get { return global::System.Linq.Enumerable.Cast<global::Sungero.Commons.ICurrency>(this.Entities); }
    }
  }

  public partial class CurrencyAnyChildEntityActions : global::Sungero.CoreEntities.Client.DatabookEntryAnyChildEntityActions
  {
  }

  public partial class CurrencyAnyChildEntityCollectionActions : global::Sungero.CoreEntities.Client.DatabookEntryAnyChildEntityCollectionActions
  {
  }

}
