
// ==================================================================
// Currency.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Commons.Client
{
  public class Currency :
    global::Sungero.CoreEntities.Client.DatabookEntry, global::Sungero.Commons.ICurrency
  {
    #region Fields and properties

    public static new readonly global::System.Guid ClassTypeGuid = global::System.Guid.Parse("ffc2629f-dc30-4106-a3ce-c402ae7d32b9");

    public override global::System.Guid TypeGuid
    {
      get { return global::Sungero.Commons.Client.Currency.ClassTypeGuid; }
    }

    public override string TypeName
    {
      get { return "Sungero.Commons.ICurrency, Sungero.Domain.Interfaces"; }
    }

      public override string DisplayValue
      {
        get { return this.Name; }
        set { this.Name = value; }
      }

      public override string DisplayPropertyName
      {
        get { return "Name"; }
      }


    public new global::Sungero.Commons.ICurrencyState State
    {
      get
      {
        return (global::Sungero.Commons.ICurrencyState)base.State;
      }
    }

    protected override global::Sungero.Domain.Shared.IEntityState CreateState()
    {
      return new global::Sungero.Commons.Shared.CurrencyState(this);
    }

    public new global::Sungero.Commons.ICurrencyInfo Info
    {
      get
      {
        return (global::Sungero.Commons.ICurrencyInfo)base.Info;
      }
    }

    public new global::Sungero.Commons.ICurrencyAccessRights AccessRights
    {
      get
      {
        return (global::Sungero.Commons.ICurrencyAccessRights)base.AccessRights;
      }
    }

    protected override global::Sungero.Domain.Shared.IEntityAccessRights CreateAccessRights()
    {
      return new global::Sungero.Commons.Client.CurrencyAccessRights(this);
    }

        protected global::Sungero.Domain.Client.SimpleProperty<global::System.String> _Name;

        public virtual global::System.String Name
        {
          get { return this._Name.Value; }
          set { this._Name.Value = value; }
        }
        protected global::Sungero.Domain.Client.SimpleProperty<global::System.String> _AlphaCode;

        public virtual global::System.String AlphaCode
        {
          get { return this._AlphaCode.Value; }
          set { this._AlphaCode.Value = value; }
        }
        protected global::Sungero.Domain.Client.SimpleProperty<global::System.String> _ShortName;

        public virtual global::System.String ShortName
        {
          get { return this._ShortName.Value; }
          set { this._ShortName.Value = value; }
        }
        protected global::Sungero.Domain.Client.SimpleProperty<global::System.String> _FractionName;

        public virtual global::System.String FractionName
        {
          get { return this._FractionName.Value; }
          set { this._FractionName.Value = value; }
        }
        protected global::Sungero.Domain.Client.SimpleProperty<global::System.Boolean?> _IsDefault;

        public virtual global::System.Boolean? IsDefault
        {
          get { return this._IsDefault.Value; }
          set { this._IsDefault.Value = value; }
        }
        protected global::Sungero.Domain.Client.SimpleProperty<global::System.String> _NumericCode;

        public virtual global::System.String NumericCode
        {
          get { return this._NumericCode.Value; }
          set { this._NumericCode.Value = value; }
        }










    #endregion

    #region Methods

    protected override object CreateActionsHandlers()
    {
      return new global::Sungero.Commons.Client.CurrencyActions(this);
    }

    protected override object CreateCollectionActionsHandlers()
    {
      return new global::Sungero.Commons.Client.CurrencyCollectionActions();
    }

    protected override object CreateAnyChildEntityActionsHandlers()
    {
      return new global::Sungero.Commons.Client.CurrencyAnyChildEntityActions();
    }

    protected override object CreateAnyChildEntityCollectionActionsHandlers()
    {
      return new global::Sungero.Commons.Client.CurrencyAnyChildEntityCollectionActions();
    }


    protected override global::Sungero.Domain.Client.EntityFunctions CreateClientFunctions()
    {
      return new global::Sungero.Commons.Client.CurrencyFunctions(this);
    }

    protected override global::Sungero.Domain.Shared.EntityFunctions CreateSharedFunctions()
    {
      return new global::Sungero.Commons.Shared.CurrencyFunctions(this);
    }
    protected override object CreateHandlers() {
      return new global::Sungero.Commons.CurrencyClientHandlers(this);
    }
    protected override object CreateSharedHandlers() {
      return new global::Sungero.Commons.CurrencySharedHandlers(this);
    }

    #endregion

    #region Framework events

    protected void NameChangedHandler()
    {
      var args = new global::Sungero.Domain.Shared.StringPropertyChangedEventArgs(this.State.Properties.Name, this.Name, this);
     ((global::Sungero.Commons.CurrencySharedHandlers)this.SharedHandlers).NameChanged(args);
    }

    protected void AlphaCodeChangedHandler()
    {
      var args = new global::Sungero.Domain.Shared.StringPropertyChangedEventArgs(this.State.Properties.AlphaCode, this.AlphaCode, this);
     ((global::Sungero.Commons.CurrencySharedHandlers)this.SharedHandlers).AlphaCodeChanged(args);
    }

    protected void ShortNameChangedHandler()
    {
      var args = new global::Sungero.Domain.Shared.StringPropertyChangedEventArgs(this.State.Properties.ShortName, this.ShortName, this);
     ((global::Sungero.Commons.CurrencySharedHandlers)this.SharedHandlers).ShortNameChanged(args);
    }

    protected void FractionNameChangedHandler()
    {
      var args = new global::Sungero.Domain.Shared.StringPropertyChangedEventArgs(this.State.Properties.FractionName, this.FractionName, this);
     ((global::Sungero.Commons.CurrencySharedHandlers)this.SharedHandlers).FractionNameChanged(args);
    }

    protected void IsDefaultChangedHandler()
    {
      var args = new global::Sungero.Domain.Shared.BooleanPropertyChangedEventArgs(this.State.Properties.IsDefault, this.IsDefault, this);
     ((global::Sungero.Commons.CurrencySharedHandlers)this.SharedHandlers).IsDefaultChanged(args);
    }

    protected void NumericCodeChangedHandler()
    {
      var args = new global::Sungero.Domain.Shared.StringPropertyChangedEventArgs(this.State.Properties.NumericCode, this.NumericCode, this);
     ((global::Sungero.Commons.CurrencySharedHandlers)this.SharedHandlers).NumericCodeChanged(args);
    }



  protected global::System.String NameValueInputHandler(global::System.String value)
  {
    var args = new global::Sungero.Presentation.StringValueInputEventArgs(this.Name, value, this, this.Info.Properties.Name);
    ((global::Sungero.Commons.CurrencyClientHandlers)this.Handlers).NameValueInput(args);
    return args.NewValue;
  }

  protected global::System.String AlphaCodeValueInputHandler(global::System.String value)
  {
    var args = new global::Sungero.Presentation.StringValueInputEventArgs(this.AlphaCode, value, this, this.Info.Properties.AlphaCode);
    ((global::Sungero.Commons.CurrencyClientHandlers)this.Handlers).AlphaCodeValueInput(args);
    return args.NewValue;
  }

  protected global::System.String ShortNameValueInputHandler(global::System.String value)
  {
    var args = new global::Sungero.Presentation.StringValueInputEventArgs(this.ShortName, value, this, this.Info.Properties.ShortName);
    ((global::Sungero.Commons.CurrencyClientHandlers)this.Handlers).ShortNameValueInput(args);
    return args.NewValue;
  }

  protected global::System.String FractionNameValueInputHandler(global::System.String value)
  {
    var args = new global::Sungero.Presentation.StringValueInputEventArgs(this.FractionName, value, this, this.Info.Properties.FractionName);
    ((global::Sungero.Commons.CurrencyClientHandlers)this.Handlers).FractionNameValueInput(args);
    return args.NewValue;
  }

  protected global::System.Boolean? IsDefaultValueInputHandler(global::System.Boolean? value)
  {
    var args = new global::Sungero.Presentation.BooleanValueInputEventArgs(this.IsDefault, value, this, this.Info.Properties.IsDefault);
    ((global::Sungero.Commons.CurrencyClientHandlers)this.Handlers).IsDefaultValueInput(args);
    return args.NewValue;
  }

  protected global::System.String NumericCodeValueInputHandler(global::System.String value)
  {
    var args = new global::Sungero.Presentation.StringValueInputEventArgs(this.NumericCode, value, this, this.Info.Properties.NumericCode);
    ((global::Sungero.Commons.CurrencyClientHandlers)this.Handlers).NumericCodeValueInput(args);
    return args.NewValue;
  }



    #endregion

    #region Constructors



    public Currency()
    {
            this._Name = new global::Sungero.Domain.Client.SimpleProperty<global::System.String>("Name", this);
            this._Name.ValueChanged += (sender, e) => { this.NameChangedHandler(); };
            this.AddProperty(this._Name);

            this._AlphaCode = new global::Sungero.Domain.Client.SimpleProperty<global::System.String>("AlphaCode", this);
            this._AlphaCode.ValueChanged += (sender, e) => { this.AlphaCodeChangedHandler(); };
            this.AddProperty(this._AlphaCode);

            this._ShortName = new global::Sungero.Domain.Client.SimpleProperty<global::System.String>("ShortName", this);
            this._ShortName.ValueChanged += (sender, e) => { this.ShortNameChangedHandler(); };
            this.AddProperty(this._ShortName);

            this._FractionName = new global::Sungero.Domain.Client.SimpleProperty<global::System.String>("FractionName", this);
            this._FractionName.ValueChanged += (sender, e) => { this.FractionNameChangedHandler(); };
            this.AddProperty(this._FractionName);

            this._IsDefault = new global::Sungero.Domain.Client.SimpleProperty<global::System.Boolean?>("IsDefault", this);
            this._IsDefault.ValueChanged += (sender, e) => { this.IsDefaultChangedHandler(); };
            this.AddProperty(this._IsDefault);

            this._NumericCode = new global::Sungero.Domain.Client.SimpleProperty<global::System.String>("NumericCode", this);
            this._NumericCode.ValueChanged += (sender, e) => { this.NumericCodeChangedHandler(); };
            this.AddProperty(this._NumericCode);








    }

    #endregion

  }
}

// ==================================================================
// CurrencyPresenter.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Commons.Client
{
  public class CurrencyPresenter<T> :
    global::Sungero.Domain.Client.EntityPresenter<T>
    where T : class, global::Sungero.Commons.ICurrency
  {
    #region Fields and properties

          private global::System.Windows.Input.ICommand _ShowDuplicatesCommand;

          public global::System.Windows.Input.ICommand ShowDuplicatesCommand
          {
            get
            {
              if (this._ShowDuplicatesCommand == null)
                  this._ShowDuplicatesCommand = new global::Sungero.Domain.Client.SingleEntityCommand<T>("ShowDuplicates", this, this.ShowDuplicates, this.CanShowDuplicates) { IsEmptyParameterAllowed = true };
              return this._ShowDuplicatesCommand;
            }
          }




    #endregion

    #region Methods

              private bool CanShowDuplicates(T entity)
              {
                var args = new global::Sungero.Domain.Client.WpfCanExecuteActionArgs(global::Sungero.Domain.Shared.FormType.Card, entity, this);
                return ((Sungero.Commons.Client.CurrencyActions)(entity as Sungero.Commons.Client.Currency).ActionsHandlers).CanShowDuplicates(args);
              }

              private void ShowDuplicates(T entity)
              {
                var args = new global::Sungero.Domain.Client.WpfExecuteActionArgs(global::Sungero.Domain.Shared.FormType.Card, entity, this, entity.Info.Actions.ShowDuplicates);
                ((Sungero.Commons.Client.CurrencyActions)(entity as Sungero.Commons.Client.Currency).ActionsHandlers).ShowDuplicates(args);
              }


    #endregion

    #region Framework events

    protected override void EntityPropertyChangedEventHandler(object sender, global::System.ComponentModel.PropertyChangedEventArgs e)
    {
      base.EntityPropertyChangedEventHandler(sender, e);
    }

    #endregion



    #region Constructors

    private void Init()
    {

    }

    public CurrencyPresenter()
    {
      this.Init();
    }

    #endregion
  }
}

// ==================================================================
// CurrencyCollectionPresenter.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Commons.Client
{
  public class CurrencyCollectionPresenter<T> : 
    global::Sungero.Domain.Client.EntityCollectionPresenter<T>
    where T: class, global::Sungero.Commons.ICurrency
  {
    #region Actions



    #endregion

    #region Methods


    #endregion

    public CurrencyCollectionPresenter(global::System.Linq.IQueryable<T> query, OnLookup onLookup)
      : base(query, onLookup)
    {
    }

    public CurrencyCollectionPresenter(global::System.Linq.IQueryable<T> query)
      : this(query, null) { }

    public CurrencyCollectionPresenter(OnLookup onLookup)
      : this(null, onLookup) { }

    public CurrencyCollectionPresenter()
      : this(null, null) { }
  }
}

// ==================================================================
// CurrencyRepositoryImplementer.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Commons.Client
{ 
  public class CurrencyRepositoryImplementer<T> : 
      global::Sungero.Domain.Client.RepositoryImplementer<T>,
      global::Sungero.Commons.ICurrencyRepositoryImplementer<T>
      where T : global::Sungero.Commons.ICurrency
    {
       public new global::Sungero.Commons.ICurrencyAccessRights AccessRights
       {
          get { return (global::Sungero.Commons.ICurrencyAccessRights)base.AccessRights; }
       }

       public new global::Sungero.Commons.ICurrencyInfo Info
       {
          get { return (global::Sungero.Commons.ICurrencyInfo)base.Info; }
       }

       protected override global::Sungero.Domain.Shared.IEntityAccessRights CreateAccessRights()
       {
         return new global::Sungero.Commons.Client.CurrencyTypeAccessRights(typeof(T));
       }
    }
}

// ==================================================================
// CurrencyAccessRights.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Commons.Client
{
  public class CurrencyAccessRights : 
    Sungero.CoreEntities.Client.DatabookEntryAccessRights, Sungero.Commons.ICurrencyAccessRights
  {

    public CurrencyAccessRights(global::Sungero.Domain.Shared.IEntity entity) : base(entity)
    {
    }
  }

  public class CurrencyTypeAccessRights : 
    Sungero.CoreEntities.Client.DatabookEntryTypeAccessRights, Sungero.Commons.ICurrencyAccessRights
  {

    public CurrencyTypeAccessRights(global::System.Type entityType) : base(entityType)
    {
    }
  }
}
