
// ==================================================================
// ConditionBaseDeliveryMethods.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Docflow.Server
{
  public class ConditionBaseDeliveryMethodsFilterForDeliveryMethod<TQueryEntity, TSourceEntity, TRootEntity>
    : global::Sungero.Domain.ChildEntityPropertyFilterBase<TQueryEntity, TSourceEntity, TRootEntity>
    where TQueryEntity : class, global::Sungero.Docflow.IMailDeliveryMethod
    where TSourceEntity : class, global::Sungero.Docflow.IConditionBaseDeliveryMethods
    where TRootEntity : class, global::Sungero.Docflow.IConditionBase
  {
    protected override global::System.Linq.IQueryable<TQueryEntity> ApplyAppliedFilter(global::System.Linq.IQueryable<TQueryEntity> query, TSourceEntity sourceEntity, TRootEntity rootEntity)
    {
      var args = new global::Sungero.Domain.PropertyFilteringEventArgs(sourceEntity);
      var result = new global::Sungero.Docflow.ConditionBaseDeliveryMethodsDeliveryMethodPropertyFilteringServerHandler<TQueryEntity>(sourceEntity, rootEntity).DeliveryMethodsDeliveryMethodFiltering(query, args);
      if (args.DisableUiFiltering)
        global::Sungero.Domain.UiFilteringEventManagementScope.DisableEvent<TQueryEntity>();
      return result;
    }

    public ConditionBaseDeliveryMethodsFilterForDeliveryMethod(string propertyName)
      : base(propertyName)
    {
    }
  }

  public class ConditionBaseDeliveryMethodsSearchFilterForDeliveryMethod<TQueryEntity>
    : global::Sungero.Domain.SearchDialogPropertyFilter<TQueryEntity>
    where TQueryEntity : class, global::Sungero.Docflow.IMailDeliveryMethod
  {
    protected override global::System.Linq.IQueryable<TQueryEntity> ApplyAppliedFilter(global::System.Linq.IQueryable<TQueryEntity> query, System.Guid entityType)
    {
      var args = new global::Sungero.Domain.PropertySearchDialogFilteringEventArgs(entityType);
      var result = new global::Sungero.Docflow.ConditionBaseDeliveryMethodsDeliveryMethodSearchPropertyFilteringServerHandler<TQueryEntity>().DeliveryMethodsDeliveryMethodSearchDialogFiltering(query, args);
      if (args.DisableUiFiltering)
          global::Sungero.Domain.UiFilteringEventManagementScope.DisableEvent<TQueryEntity>();
      return result;
    }

    public ConditionBaseDeliveryMethodsSearchFilterForDeliveryMethod(string propertyName)
      : base(propertyName)
    {
    }
  }



  [global::Sungero.Domain.PropertyFilter(typeof(global::Sungero.Docflow.Server.ConditionBaseDeliveryMethodsFilterForDeliveryMethod<global::Sungero.Docflow.IMailDeliveryMethod, global::Sungero.Docflow.IConditionBaseDeliveryMethods, global::Sungero.Docflow.IConditionBase>), "DeliveryMethod")]
  [global::Sungero.Domain.SearchPropertyFilter(typeof(global::Sungero.Docflow.Server.ConditionBaseDeliveryMethodsSearchFilterForDeliveryMethod<global::Sungero.Docflow.IMailDeliveryMethod>), "DeliveryMethod")]


  public class ConditionBaseDeliveryMethods :
    global::Sungero.Domain.ChildEntity, global::Sungero.Docflow.IConditionBaseDeliveryMethods
  {
    public static new readonly global::System.Guid ClassTypeGuid = global::System.Guid.Parse("7ec8485f-cc13-4da1-bfdb-a9a5f7473e26");

    public override global::System.Guid TypeGuid
    {
      get { return global::Sungero.Docflow.Server.ConditionBaseDeliveryMethods.ClassTypeGuid; }
    }

    public override string TypeName
    {
      get { return "Sungero.Docflow.IConditionBaseDeliveryMethods, Sungero.Domain.Interfaces"; }
    }

    public new virtual global::Sungero.Docflow.IConditionBaseDeliveryMethodsState State
    {
      get { return (global::Sungero.Docflow.IConditionBaseDeliveryMethodsState)base.State; }
    }

    protected override global::Sungero.Domain.Shared.IEntityState CreateState()
    {
      return new global::Sungero.Docflow.Shared.ConditionBaseDeliveryMethodsState(this);
    }

    public new virtual global::Sungero.Docflow.IConditionBaseDeliveryMethodsInfo Info
    {
      get { return (global::Sungero.Docflow.IConditionBaseDeliveryMethodsInfo)base.Info; }
    }


    public global::Sungero.Docflow.IConditionBase ConditionBase { get; set; }

    public override global::Sungero.Domain.Shared.IEntity RootEntity
    {
      get { return this.ConditionBase; }
      set { this.ConditionBase = (global::Sungero.Docflow.IConditionBase)value; }
    }

    protected override object CreateSharedHandlers() {
      return new global::Sungero.Docflow.ConditionBaseDeliveryMethodsSharedHandlers(this);
    }







    private global::Sungero.Docflow.IMailDeliveryMethod _DeliveryMethod;
    public virtual global::Sungero.Docflow.IMailDeliveryMethod DeliveryMethod
    {
      get
      {
        return this._DeliveryMethod;
      }

      set
      {
        this.SetPropertyValue("DeliveryMethod", this._DeliveryMethod, value, (propertyValue) => { this._DeliveryMethod = propertyValue; }, this.DeliveryMethodChangedHandler);
      }
    }




    #region Framework events

    protected void DeliveryMethodChangedHandler()
    {
      var args = new global::Sungero.Docflow.Shared.ConditionBaseDeliveryMethodsDeliveryMethodChangedEventArgs(this.State.Properties.DeliveryMethod, this.DeliveryMethod, this);
     ((global::Sungero.Docflow.ConditionBaseDeliveryMethodsSharedHandlers)this.SharedHandlers).DeliveryMethodsDeliveryMethodChanged(args);
    }



    #endregion


    public ConditionBaseDeliveryMethods()
    {
    }

  }
}

// ==================================================================
// ConditionBaseDeliveryMethodsHandlers.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Docflow
{
  public partial class ConditionBaseDeliveryMethodsDeliveryMethodPropertyFilteringServerHandler<T>
    : global::Sungero.Domain.ChildEntityPropertyFilteringServerHandler
    where T : class, global::Sungero.Docflow.IMailDeliveryMethod
  {
    private global::Sungero.Docflow.IConditionBaseDeliveryMethods _obj
    {
      get { return (global::Sungero.Docflow.IConditionBaseDeliveryMethods)this.Entity; }
    }

    private global::Sungero.Docflow.IConditionBase _root
    {
      get { return (global::Sungero.Docflow.IConditionBase)this.Root; }
    }

    public virtual global::System.Linq.IQueryable<T> DeliveryMethodsDeliveryMethodFiltering(global::System.Linq.IQueryable<T> query, global::Sungero.Domain.PropertyFilteringEventArgs e)
    {
      return query;
    }

    public ConditionBaseDeliveryMethodsDeliveryMethodPropertyFilteringServerHandler(global::Sungero.Docflow.IConditionBaseDeliveryMethods entity, global::Sungero.Docflow.IConditionBase root)
      : base(entity, root)
    {
    }
  }

  public partial class ConditionBaseDeliveryMethodsDeliveryMethodSearchPropertyFilteringServerHandler<T>
    : global::Sungero.Domain.SearchPropertyFilteringServerHandler
    where T : class, global::Sungero.Docflow.IMailDeliveryMethod
  {

    public virtual global::System.Linq.IQueryable<T> DeliveryMethodsDeliveryMethodSearchDialogFiltering(global::System.Linq.IQueryable<T> query, global::Sungero.Domain.PropertySearchDialogFilteringEventArgs e)
    {
      return query;
    }

    public ConditionBaseDeliveryMethodsDeliveryMethodSearchPropertyFilteringServerHandler()
      : base()
    {
    }
  }



}

// ==================================================================
// ConditionBaseDeliveryMethodsEventArgs.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Docflow.Server
{
}
