
// ==================================================================
// ApprovalTaskObserversState.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Docflow.Shared
{
  public class ApprovalTaskObserversState : 
    global::Sungero.Workflow.Shared.TaskObserversState, global::Sungero.Docflow.IApprovalTaskObserversState
  {
    public ApprovalTaskObserversState(global::Sungero.Docflow.IApprovalTaskObservers entity) : base(entity) { }

    public new global::Sungero.Docflow.IApprovalTaskObserversPropertyStates Properties
    {
      get { return (global::Sungero.Docflow.IApprovalTaskObserversPropertyStates)base.Properties; }
    }

    protected override global::Sungero.Domain.Shared.IEntityPropertyStates CreatePropertyStates(global::Sungero.Domain.Shared.IEntity entity)
    {
      return new global::Sungero.Docflow.Shared.ApprovalTaskObserversPropertyStates(entity);
    }


  }


  public class ApprovalTaskObserversPropertyStates : 
    global::Sungero.Workflow.Shared.TaskObserversPropertyStates, global::Sungero.Docflow.IApprovalTaskObserversPropertyStates
  {
            public new global::Sungero.Domain.Shared.IPropertyState<global::Sungero.Docflow.IApprovalTask> Task
            {
              get { return (global::Sungero.Domain.Shared.IPropertyState<global::Sungero.Docflow.IApprovalTask>)base.Task; }
            }

            protected override global::Sungero.Domain.Shared.IPropertyState<global::Sungero.Workflow.ITask> InternalTask
            {
              get { return this.GetPropertyState<global::Sungero.Docflow.IApprovalTask>("Task"); }
            }


    protected internal ApprovalTaskObserversPropertyStates(global::Sungero.Domain.Shared.IEntity entity) : base(entity) { }
  }

  public class ApprovalTaskObserversCollectionPropertyState<T> :
    global::Sungero.Workflow.Shared.TaskObserversCollectionPropertyState<T>, global::Sungero.Docflow.IApprovalTaskObserversCollectionPropertyState<T>
    where T : global::Sungero.Docflow.IApprovalTaskObservers
  {
    public new global::Sungero.Docflow.IApprovalTaskObserversCollectionPropertyStates Properties
    {
      get { return (global::Sungero.Docflow.IApprovalTaskObserversCollectionPropertyStates)base.Properties; }
    }

    protected override global::Sungero.Domain.Shared.IChildEntityCollectionPropertyStates CreatePropertyStates()
    {
      return new global::Sungero.Docflow.Shared.ApprovalTaskObserversCollectionPropertyStates(this.ChildEntityMetadata);
    }

    protected internal ApprovalTaskObserversCollectionPropertyState(global::Sungero.Domain.Shared.IEntity entity, string propertyName) : base(entity, propertyName) { }
  }

  public class ApprovalTaskObserversCollectionPropertyStates :
    global::Sungero.Workflow.Shared.TaskObserversCollectionPropertyStates, global::Sungero.Docflow.IApprovalTaskObserversCollectionPropertyStates
  {

    protected internal ApprovalTaskObserversCollectionPropertyStates(global::Sungero.Metadata.EntityMetadata childEntityMetadata) : base(childEntityMetadata) { }
  }
}

// ==================================================================
// ApprovalTaskObserversEventArgs.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Docflow.Shared
{  
}

// ==================================================================
// ApprovalTaskObserversInfo.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Docflow.Shared
{
  public class ApprovalTaskObserversInfo : 
    global::Sungero.Workflow.Shared.TaskObserversInfo, global::Sungero.Docflow.IApprovalTaskObserversInfo
  {
    public ApprovalTaskObserversInfo(global::System.Type entityType) : base(entityType) { }

    public new global::Sungero.Docflow.IApprovalTaskObserversPropertiesInfo Properties
    {
      get { return (global::Sungero.Docflow.IApprovalTaskObserversPropertiesInfo)base.Properties; }
    }

    protected override global::Sungero.Domain.Shared.IEntityPropertiesInfo CreateEntityPropertiesInfo(global::System.Type entityType)
    {
      return new global::Sungero.Docflow.Shared.ApprovalTaskObserversPropertiesInfo(entityType);
    }

  }

  public class ApprovalTaskObserversPropertiesInfo : 
    global::Sungero.Workflow.Shared.TaskObserversPropertiesInfo, global::Sungero.Docflow.IApprovalTaskObserversPropertiesInfo
  {
        public new global::Sungero.Domain.Shared.INavigationPropertyInfo<global::Sungero.Docflow.IApprovalTaskInfo, global::Sungero.Docflow.IApprovalTask> Task
        {
          get
          {
             var propertyMetadata = this.GetPropertyMetadata<global::Sungero.Metadata.NavigationPropertyMetadata>("Task");
             return new global::Sungero.Domain.Shared.NavigationPropertyInfo<global::Sungero.Docflow.IApprovalTaskInfo, global::Sungero.Docflow.IApprovalTask>(propertyMetadata);
          }
        }


    protected internal ApprovalTaskObserversPropertiesInfo(global::System.Type entityType) : base(entityType) { }
  }

}
