
// ==================================================================
// RegistrationGroupEventArgs.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Docflow.Client
{ 
  public class RegistrationGroupResponsibleEmployeeValueInputEventArgs : global::Sungero.Presentation.ValueInputEventArgs<global::Sungero.Company.IEmployee>
  {
    public RegistrationGroupResponsibleEmployeeValueInputEventArgs(global::Sungero.Company.IEmployee oldValue, global::Sungero.Company.IEmployee newValue, global::Sungero.Domain.Shared.IEntity entity, global::Sungero.Domain.Shared.IPropertyInfo propertyInfo): base(oldValue, newValue, entity, propertyInfo) { }
  }






}

// ==================================================================
// RegistrationGroupHandlers.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Docflow
{

  public partial class RegistrationGroupFilteringClientHandler
    : global::Sungero.Domain.EntityFilteringClientHandler
  {
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    protected global::Sungero.Docflow.IRegistrationGroupFilterState Filter { get; private set; }

    private global::Sungero.Docflow.IRegistrationGroupFilterState _filter
    {
      get
      {
        return this.Filter;
      }
    }

    public RegistrationGroupFilteringClientHandler(global::Sungero.Docflow.IRegistrationGroupFilterState filter)
    : base()
    {
      this.Filter = filter;
    }

    protected RegistrationGroupFilteringClientHandler()
    {
    }

    public override void ValidateFilterPanel(global::Sungero.Domain.Client.ValidateFilterPanelEventArgs e)
    {
    }
  }


  public partial class RegistrationGroupClientHandlers : global::Sungero.CoreEntities.GroupClientHandlers
  {
    private global::Sungero.Docflow.IRegistrationGroup _obj
    {
      get { return (global::Sungero.Docflow.IRegistrationGroup)this.Entity; }
    }

    public virtual void IndexValueInput(global::Sungero.Presentation.StringValueInputEventArgs e) { }


    public virtual void ResponsibleEmployeeValueInput(global::Sungero.Docflow.Client.RegistrationGroupResponsibleEmployeeValueInputEventArgs e) { }



    public virtual void CanRegisterIncomingValueInput(global::Sungero.Presentation.BooleanValueInputEventArgs e) { }


    public virtual void CanRegisterOutgoingValueInput(global::Sungero.Presentation.BooleanValueInputEventArgs e) { }


    public virtual void CanRegisterInternalValueInput(global::Sungero.Presentation.BooleanValueInputEventArgs e) { }


    public virtual void CanRegisterContractualValueInput(global::Sungero.Presentation.BooleanValueInputEventArgs e) { }


    public RegistrationGroupClientHandlers(global::Sungero.Docflow.IRegistrationGroup entity) : base(entity)
    {
    }
  }

  public partial class RegistrationGroupDepartmentsClientHandlers : global::Sungero.Domain.Shared.ChildEntityClientHandlers
  {
    private global::Sungero.Docflow.IRegistrationGroupDepartments _obj
    {
      get { return (global::Sungero.Docflow.IRegistrationGroupDepartments)this.Entity; }
    }
    public virtual void DepartmentsDepartmentValueInput(global::Sungero.Docflow.Client.RegistrationGroupDepartmentsDepartmentValueInputEventArgs e) { }


    public RegistrationGroupDepartmentsClientHandlers(global::Sungero.Docflow.IRegistrationGroupDepartments entity) : base(entity)
    {
    }
  }

}

// ==================================================================
// RegistrationGroupClientFunctions.g.cs
// ==================================================================

namespace Sungero.Docflow.Client
{
  public partial class RegistrationGroupFunctions : global::Sungero.CoreEntities.Client.GroupFunctions
  {
    private global::Sungero.Docflow.IRegistrationGroup _obj
    {
      get { return (global::Sungero.Docflow.IRegistrationGroup)this.Entity; }
    }

    public RegistrationGroupFunctions(global::Sungero.Docflow.IRegistrationGroup entity) : base(entity) { }
  }
}

// ==================================================================
// RegistrationGroupFunctions.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Docflow.Functions
{
  internal static class RegistrationGroup
  {
    internal static class Remote
    {
      /// <redirect project="Sungero.Docflow.Server" type="Sungero.Docflow.Server.RegistrationGroupFunctions" />
      internal static  global::System.Linq.IQueryable<global::Sungero.Docflow.IDocumentRegister> GetGroupDocumentRegisters(global::Sungero.Docflow.IRegistrationGroup registrationGroup)
      {
        return global::Sungero.Domain.Shared.RemoteFunctionExecutor.ExecuteWithResult<global::System.Linq.IQueryable<global::Sungero.Docflow.IDocumentRegister>>(
          global::System.Guid.Parse("6eddf9a4-bf7b-4cac-961b-a1f0f0bc7ab6"),
          "GetGroupDocumentRegisters(global::Sungero.Docflow.IRegistrationGroup)"
          , registrationGroup);
      }

    }
  }
}

// ==================================================================
// RegistrationGroupClientPublicFunctions.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Docflow.Client
{
  public class RegistrationGroupClientPublicFunctions : global::Sungero.Docflow.Client.IRegistrationGroupClientPublicFunctions
  {
  }
}

// ==================================================================
// RegistrationGroupActions.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Docflow.Client
{
  public partial class RegistrationGroupActions : global::Sungero.CoreEntities.Client.GroupActions
  {
    private global::Sungero.Docflow.IRegistrationGroup _obj { get { return (global::Sungero.Docflow.IRegistrationGroup)this.Entity; } }
    public RegistrationGroupActions(global::Sungero.Docflow.IRegistrationGroup entity) : base(entity) { }
  }

  public partial class RegistrationGroupCollectionActions : global::Sungero.CoreEntities.Client.GroupCollectionActions
  {
    private global::System.Collections.Generic.IEnumerable<global::Sungero.Docflow.IRegistrationGroup> _objs
    { 
      get { return global::System.Linq.Enumerable.Cast<global::Sungero.Docflow.IRegistrationGroup>(this.Entities); }
    }
  }

  public partial class RegistrationGroupAnyChildEntityActions : global::Sungero.CoreEntities.Client.GroupAnyChildEntityActions
  {
  }

  public partial class RegistrationGroupAnyChildEntityCollectionActions : global::Sungero.CoreEntities.Client.GroupAnyChildEntityCollectionActions
  {
  }

}
