
// ==================================================================
// CounterpartyDocumentTrackingState.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Docflow.Shared
{
  public class CounterpartyDocumentTrackingState : 
    global::Sungero.Docflow.Shared.InternalDocumentBaseTrackingState, global::Sungero.Docflow.ICounterpartyDocumentTrackingState
  {
    public CounterpartyDocumentTrackingState(global::Sungero.Docflow.ICounterpartyDocumentTracking entity) : base(entity) { }

    public new global::Sungero.Docflow.ICounterpartyDocumentTrackingPropertyStates Properties
    {
      get { return (global::Sungero.Docflow.ICounterpartyDocumentTrackingPropertyStates)base.Properties; }
    }

    protected override global::Sungero.Domain.Shared.IEntityPropertyStates CreatePropertyStates(global::Sungero.Domain.Shared.IEntity entity)
    {
      return new global::Sungero.Docflow.Shared.CounterpartyDocumentTrackingPropertyStates(entity);
    }


  }


  public class CounterpartyDocumentTrackingPropertyStates : 
    global::Sungero.Docflow.Shared.InternalDocumentBaseTrackingPropertyStates, global::Sungero.Docflow.ICounterpartyDocumentTrackingPropertyStates
  {
            public new global::Sungero.Domain.Shared.IPropertyState<global::Sungero.Docflow.ICounterpartyDocument> OfficialDocument
            {
              get { return (global::Sungero.Domain.Shared.IPropertyState<global::Sungero.Docflow.ICounterpartyDocument>)base.OfficialDocument; }
            }

            protected override global::Sungero.Domain.Shared.IPropertyState<global::Sungero.Docflow.IOfficialDocument> InternalOfficialDocument
            {
              get { return this.GetPropertyState<global::Sungero.Docflow.ICounterpartyDocument>("OfficialDocument"); }
            }


    protected internal CounterpartyDocumentTrackingPropertyStates(global::Sungero.Domain.Shared.IEntity entity) : base(entity) { }
  }

  public class CounterpartyDocumentTrackingCollectionPropertyState<T> :
    global::Sungero.Docflow.Shared.InternalDocumentBaseTrackingCollectionPropertyState<T>, global::Sungero.Docflow.ICounterpartyDocumentTrackingCollectionPropertyState<T>
    where T : global::Sungero.Docflow.ICounterpartyDocumentTracking
  {
    public new global::Sungero.Docflow.ICounterpartyDocumentTrackingCollectionPropertyStates Properties
    {
      get { return (global::Sungero.Docflow.ICounterpartyDocumentTrackingCollectionPropertyStates)base.Properties; }
    }

    protected override global::Sungero.Domain.Shared.IChildEntityCollectionPropertyStates CreatePropertyStates()
    {
      return new global::Sungero.Docflow.Shared.CounterpartyDocumentTrackingCollectionPropertyStates(this.ChildEntityMetadata);
    }

    protected internal CounterpartyDocumentTrackingCollectionPropertyState(global::Sungero.Domain.Shared.IEntity entity, string propertyName) : base(entity, propertyName) { }
  }

  public class CounterpartyDocumentTrackingCollectionPropertyStates :
    global::Sungero.Docflow.Shared.InternalDocumentBaseTrackingCollectionPropertyStates, global::Sungero.Docflow.ICounterpartyDocumentTrackingCollectionPropertyStates
  {

    protected internal CounterpartyDocumentTrackingCollectionPropertyStates(global::Sungero.Metadata.EntityMetadata childEntityMetadata) : base(childEntityMetadata) { }
  }
}

// ==================================================================
// CounterpartyDocumentTrackingEventArgs.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Docflow.Shared
{  
}

// ==================================================================
// CounterpartyDocumentTrackingInfo.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Docflow.Shared
{
  public class CounterpartyDocumentTrackingInfo : 
    global::Sungero.Docflow.Shared.InternalDocumentBaseTrackingInfo, global::Sungero.Docflow.ICounterpartyDocumentTrackingInfo
  {
    public CounterpartyDocumentTrackingInfo(global::System.Type entityType) : base(entityType) { }

    public new global::Sungero.Docflow.ICounterpartyDocumentTrackingPropertiesInfo Properties
    {
      get { return (global::Sungero.Docflow.ICounterpartyDocumentTrackingPropertiesInfo)base.Properties; }
    }

    protected override global::Sungero.Domain.Shared.IEntityPropertiesInfo CreateEntityPropertiesInfo(global::System.Type entityType)
    {
      return new global::Sungero.Docflow.Shared.CounterpartyDocumentTrackingPropertiesInfo(entityType);
    }

  }

  public class CounterpartyDocumentTrackingPropertiesInfo : 
    global::Sungero.Docflow.Shared.InternalDocumentBaseTrackingPropertiesInfo, global::Sungero.Docflow.ICounterpartyDocumentTrackingPropertiesInfo
  {
        public new global::Sungero.Domain.Shared.INavigationPropertyInfo<global::Sungero.Docflow.ICounterpartyDocumentInfo, global::Sungero.Docflow.ICounterpartyDocument> OfficialDocument
        {
          get
          {
             var propertyMetadata = this.GetPropertyMetadata<global::Sungero.Metadata.NavigationPropertyMetadata>("OfficialDocument");
             return new global::Sungero.Domain.Shared.NavigationPropertyInfo<global::Sungero.Docflow.ICounterpartyDocumentInfo, global::Sungero.Docflow.ICounterpartyDocument>(propertyMetadata);
          }
        }


    protected internal CounterpartyDocumentTrackingPropertiesInfo(global::System.Type entityType) : base(entityType) { }
  }

}
