
// ==================================================================
// FinArchiveExportReport.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.FinancialArchive.Client
{
  public class FinArchiveExportReport : global::Sungero.Reporting.Client.Report, global::Sungero.FinancialArchive.IFinArchiveExportReport
  {
    public static readonly new global::System.Guid ClassTypeGuid = new global::System.Guid("e5081ffe-8a47-41fd-ad9f-407d1b181464");

    protected override global::System.Guid ReportTypeId
    {
      get { return ClassTypeGuid; }
    }



    public global::System.Nullable<global::System.DateTime> CurrentTime
    {
      get
      {
          return this.GetParameterValue("CurrentTime") as global::System.Nullable<global::System.DateTime>;
      }

      set
      {
        this.SetParameterValue("CurrentTime", value);
      }
    }

    public global::System.String ReportSessionId
    {
      get
      {
          return this.GetParameterValue("ReportSessionId") as global::System.String;
      }

      set
      {
        this.SetParameterValue("ReportSessionId", value);
      }
    }

    public global::System.Nullable<global::System.Int32> Exported
    {
      get
      {
          return this.GetParameterValue("Exported") as global::System.Nullable<global::System.Int32>;
      }

      set
      {
        this.SetParameterValue("Exported", value);
      }
    }

    public global::System.Nullable<global::System.Int32> NotExported
    {
      get
      {
          return this.GetParameterValue("NotExported") as global::System.Nullable<global::System.Int32>;
      }

      set
      {
        this.SetParameterValue("NotExported", value);
      }
    }


    public FinArchiveExportReport()
    {
      this.Handlers = new global::Sungero.FinancialArchive.FinArchiveExportReportClientHandlers(this);
    }
  }
}

// ==================================================================
// FinArchiveExportReportRepositoryImplementer.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.FinancialArchive.Client
{ 
  public class FinArchiveExportReportRepositoryImplementer<T> : 
      global::Sungero.Reporting.Client.ReportRepositoryImplementer<T>,
      global::Sungero.FinancialArchive.IFinArchiveExportReportRepositoryImplementer<T>
      where T : global::Sungero.FinancialArchive.IFinArchiveExportReport
    {
    }
}
