//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Docflow.Client
{
  /// <summary>
  /// Interaction logic for ApprovalSimpleNotificationCollectionView.xaml.
  /// </summary>
  public partial class ApprovalSimpleNotificationCollectionView : global::System.Windows.Controls.UserControl
  {
    public ApprovalSimpleNotificationCollectionView()
    {
      InitializeComponent();
    }
  }
}