
// ==================================================================
// AcquaintanceTaskPerformersState.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.RecordManagement.Shared
{
  public class AcquaintanceTaskPerformersState : 
    global::Sungero.Domain.Shared.ChildEntityState, global::Sungero.RecordManagement.IAcquaintanceTaskPerformersState
  {
    public AcquaintanceTaskPerformersState(global::Sungero.RecordManagement.IAcquaintanceTaskPerformers entity) : base(entity) { }

    public new global::Sungero.RecordManagement.IAcquaintanceTaskPerformersPropertyStates Properties
    {
      get { return (global::Sungero.RecordManagement.IAcquaintanceTaskPerformersPropertyStates)base.Properties; }
    }

    protected override global::Sungero.Domain.Shared.IEntityPropertyStates CreatePropertyStates(global::Sungero.Domain.Shared.IEntity entity)
    {
      return new global::Sungero.RecordManagement.Shared.AcquaintanceTaskPerformersPropertyStates(entity);
    }


  }


  public class AcquaintanceTaskPerformersPropertyStates : 
    global::Sungero.Domain.Shared.ChildEntityPropertyStates, global::Sungero.RecordManagement.IAcquaintanceTaskPerformersPropertyStates
  {
            public global::Sungero.Domain.Shared.IPropertyState<global::Sungero.RecordManagement.IAcquaintanceTask> AcquaintanceTask 
            {
              get { return this.InternalAcquaintanceTask; }
            }

            protected virtual global::Sungero.Domain.Shared.IPropertyState<global::Sungero.RecordManagement.IAcquaintanceTask> InternalAcquaintanceTask
            {
              get { return this.GetPropertyState<global::Sungero.RecordManagement.IAcquaintanceTask>("AcquaintanceTask"); }
            }
            public global::Sungero.Domain.Shared.IPropertyState<global::Sungero.CoreEntities.IRecipient> Performer 
            {
              get { return this.InternalPerformer; }
            }

            protected virtual global::Sungero.Domain.Shared.IPropertyState<global::Sungero.CoreEntities.IRecipient> InternalPerformer
            {
              get { return this.GetPropertyState<global::Sungero.CoreEntities.IRecipient>("Performer"); }
            }


    protected internal AcquaintanceTaskPerformersPropertyStates(global::Sungero.Domain.Shared.IEntity entity) : base(entity) { }
  }

  public class AcquaintanceTaskPerformersCollectionPropertyState<T> :
    global::Sungero.Domain.Shared.ChildEntityCollectionPropertyState<T>, global::Sungero.RecordManagement.IAcquaintanceTaskPerformersCollectionPropertyState<T>
    where T : global::Sungero.RecordManagement.IAcquaintanceTaskPerformers
  {
    public new global::Sungero.RecordManagement.IAcquaintanceTaskPerformersCollectionPropertyStates Properties
    {
      get { return (global::Sungero.RecordManagement.IAcquaintanceTaskPerformersCollectionPropertyStates)base.Properties; }
    }

    protected override global::Sungero.Domain.Shared.IChildEntityCollectionPropertyStates CreatePropertyStates()
    {
      return new global::Sungero.RecordManagement.Shared.AcquaintanceTaskPerformersCollectionPropertyStates(this.ChildEntityMetadata);
    }

    protected internal AcquaintanceTaskPerformersCollectionPropertyState(global::Sungero.Domain.Shared.IEntity entity, string propertyName) : base(entity, propertyName) { }
  }

  public class AcquaintanceTaskPerformersCollectionPropertyStates :
    global::Sungero.Domain.Shared.ChildEntityCollectionPropertyStates, global::Sungero.RecordManagement.IAcquaintanceTaskPerformersCollectionPropertyStates
  {
        public global::Sungero.Domain.Shared.IChildPropertySummaryState AcquaintanceTask
        {
          get { return this.GetChildPropertySummaryState("AcquaintanceTask"); }
        }
        public global::Sungero.Domain.Shared.IChildPropertySummaryState Performer
        {
          get { return this.GetChildPropertySummaryState("Performer"); }
        }


    protected internal AcquaintanceTaskPerformersCollectionPropertyStates(global::Sungero.Metadata.EntityMetadata childEntityMetadata) : base(childEntityMetadata) { }
  }
}

// ==================================================================
// AcquaintanceTaskPerformersEventArgs.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.RecordManagement.Shared
{  
    public class AcquaintanceTaskPerformersPerformerChangedEventArgs : global::Sungero.Domain.Shared.PropertyChangedEventArgs<global::Sungero.CoreEntities.IRecipient>
    {
      public AcquaintanceTaskPerformersPerformerChangedEventArgs(global::Sungero.Domain.Shared.IPropertyState<global::Sungero.CoreEntities.IRecipient> state, global::Sungero.CoreEntities.IRecipient newValue, global::Sungero.Domain.Shared.IEntity entity): base(state, newValue, entity) { }
    }

}

// ==================================================================
// AcquaintanceTaskPerformersInfo.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.RecordManagement.Shared
{
  public class AcquaintanceTaskPerformersInfo : 
    global::Sungero.Domain.Shared.ChildEntityInfo, global::Sungero.RecordManagement.IAcquaintanceTaskPerformersInfo
  {
    public AcquaintanceTaskPerformersInfo(global::System.Type entityType) : base(entityType) { }

    public new global::Sungero.RecordManagement.IAcquaintanceTaskPerformersPropertiesInfo Properties
    {
      get { return (global::Sungero.RecordManagement.IAcquaintanceTaskPerformersPropertiesInfo)base.Properties; }
    }

    protected override global::Sungero.Domain.Shared.IEntityPropertiesInfo CreateEntityPropertiesInfo(global::System.Type entityType)
    {
      return new global::Sungero.RecordManagement.Shared.AcquaintanceTaskPerformersPropertiesInfo(entityType);
    }

  }

  public class AcquaintanceTaskPerformersPropertiesInfo : 
    global::Sungero.Domain.Shared.ChildEntityPropertiesInfo, global::Sungero.RecordManagement.IAcquaintanceTaskPerformersPropertiesInfo
  {
        public global::Sungero.Domain.Shared.INavigationPropertyInfo<global::Sungero.RecordManagement.IAcquaintanceTaskInfo, global::Sungero.RecordManagement.IAcquaintanceTask> AcquaintanceTask 
        {
          get
          {
             var propertyMetadata = this.GetPropertyMetadata<global::Sungero.Metadata.NavigationPropertyMetadata>("AcquaintanceTask");
             return new global::Sungero.Domain.Shared.NavigationPropertyInfo<global::Sungero.RecordManagement.IAcquaintanceTaskInfo, global::Sungero.RecordManagement.IAcquaintanceTask>(propertyMetadata);
          }
        }
        public global::Sungero.Domain.Shared.INavigationPropertyInfo<global::Sungero.CoreEntities.IRecipientInfo, global::Sungero.CoreEntities.IRecipient> Performer 
        {
          get
          {
             var propertyMetadata = this.GetPropertyMetadata<global::Sungero.Metadata.NavigationPropertyMetadata>("Performer");
             return new global::Sungero.Domain.Shared.NavigationPropertyInfo<global::Sungero.CoreEntities.IRecipientInfo, global::Sungero.CoreEntities.IRecipient>(propertyMetadata);
          }
        }


    protected internal AcquaintanceTaskPerformersPropertiesInfo(global::System.Type entityType) : base(entityType) { }
  }

}
