
// ==================================================================
// OutgoingLetterAddresseesState.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.RecordManagement.Shared
{
  public class OutgoingLetterAddresseesState : 
    global::Sungero.Docflow.Shared.OutgoingDocumentBaseAddresseesState, global::Sungero.RecordManagement.IOutgoingLetterAddresseesState
  {
    public OutgoingLetterAddresseesState(global::Sungero.RecordManagement.IOutgoingLetterAddressees entity) : base(entity) { }

    public new global::Sungero.RecordManagement.IOutgoingLetterAddresseesPropertyStates Properties
    {
      get { return (global::Sungero.RecordManagement.IOutgoingLetterAddresseesPropertyStates)base.Properties; }
    }

    protected override global::Sungero.Domain.Shared.IEntityPropertyStates CreatePropertyStates(global::Sungero.Domain.Shared.IEntity entity)
    {
      return new global::Sungero.RecordManagement.Shared.OutgoingLetterAddresseesPropertyStates(entity);
    }


  }


  public class OutgoingLetterAddresseesPropertyStates : 
    global::Sungero.Docflow.Shared.OutgoingDocumentBaseAddresseesPropertyStates, global::Sungero.RecordManagement.IOutgoingLetterAddresseesPropertyStates
  {
            public new global::Sungero.Domain.Shared.IPropertyState<global::Sungero.RecordManagement.IOutgoingLetter> OutgoingDocumentBase
            {
              get { return (global::Sungero.Domain.Shared.IPropertyState<global::Sungero.RecordManagement.IOutgoingLetter>)base.OutgoingDocumentBase; }
            }

            protected override global::Sungero.Domain.Shared.IPropertyState<global::Sungero.Docflow.IOutgoingDocumentBase> InternalOutgoingDocumentBase
            {
              get { return this.GetPropertyState<global::Sungero.RecordManagement.IOutgoingLetter>("OutgoingDocumentBase"); }
            }


    protected internal OutgoingLetterAddresseesPropertyStates(global::Sungero.Domain.Shared.IEntity entity) : base(entity) { }
  }

  public class OutgoingLetterAddresseesCollectionPropertyState<T> :
    global::Sungero.Docflow.Shared.OutgoingDocumentBaseAddresseesCollectionPropertyState<T>, global::Sungero.RecordManagement.IOutgoingLetterAddresseesCollectionPropertyState<T>
    where T : global::Sungero.RecordManagement.IOutgoingLetterAddressees
  {
    public new global::Sungero.RecordManagement.IOutgoingLetterAddresseesCollectionPropertyStates Properties
    {
      get { return (global::Sungero.RecordManagement.IOutgoingLetterAddresseesCollectionPropertyStates)base.Properties; }
    }

    protected override global::Sungero.Domain.Shared.IChildEntityCollectionPropertyStates CreatePropertyStates()
    {
      return new global::Sungero.RecordManagement.Shared.OutgoingLetterAddresseesCollectionPropertyStates(this.ChildEntityMetadata);
    }

    protected internal OutgoingLetterAddresseesCollectionPropertyState(global::Sungero.Domain.Shared.IEntity entity, string propertyName) : base(entity, propertyName) { }
  }

  public class OutgoingLetterAddresseesCollectionPropertyStates :
    global::Sungero.Docflow.Shared.OutgoingDocumentBaseAddresseesCollectionPropertyStates, global::Sungero.RecordManagement.IOutgoingLetterAddresseesCollectionPropertyStates
  {

    protected internal OutgoingLetterAddresseesCollectionPropertyStates(global::Sungero.Metadata.EntityMetadata childEntityMetadata) : base(childEntityMetadata) { }
  }
}

// ==================================================================
// OutgoingLetterAddresseesEventArgs.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.RecordManagement.Shared
{  
}

// ==================================================================
// OutgoingLetterAddresseesInfo.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.RecordManagement.Shared
{
  public class OutgoingLetterAddresseesInfo : 
    global::Sungero.Docflow.Shared.OutgoingDocumentBaseAddresseesInfo, global::Sungero.RecordManagement.IOutgoingLetterAddresseesInfo
  {
    public OutgoingLetterAddresseesInfo(global::System.Type entityType) : base(entityType) { }

    public new global::Sungero.RecordManagement.IOutgoingLetterAddresseesPropertiesInfo Properties
    {
      get { return (global::Sungero.RecordManagement.IOutgoingLetterAddresseesPropertiesInfo)base.Properties; }
    }

    protected override global::Sungero.Domain.Shared.IEntityPropertiesInfo CreateEntityPropertiesInfo(global::System.Type entityType)
    {
      return new global::Sungero.RecordManagement.Shared.OutgoingLetterAddresseesPropertiesInfo(entityType);
    }

  }

  public class OutgoingLetterAddresseesPropertiesInfo : 
    global::Sungero.Docflow.Shared.OutgoingDocumentBaseAddresseesPropertiesInfo, global::Sungero.RecordManagement.IOutgoingLetterAddresseesPropertiesInfo
  {
        public new global::Sungero.Domain.Shared.INavigationPropertyInfo<global::Sungero.RecordManagement.IOutgoingLetterInfo, global::Sungero.RecordManagement.IOutgoingLetter> OutgoingDocumentBase
        {
          get
          {
             var propertyMetadata = this.GetPropertyMetadata<global::Sungero.Metadata.NavigationPropertyMetadata>("OutgoingDocumentBase");
             return new global::Sungero.Domain.Shared.NavigationPropertyInfo<global::Sungero.RecordManagement.IOutgoingLetterInfo, global::Sungero.RecordManagement.IOutgoingLetter>(propertyMetadata);
          }
        }


    protected internal OutgoingLetterAddresseesPropertiesInfo(global::System.Type entityType) : base(entityType) { }
  }

}
